### ISSUE TITLE
Small UI Fixes.

### ISSUE THREAD

**Issue by namchester** [crowdresearch/crowdsource-platform#115]
Ill be fixing small UI glitches here and there.

**Comment by neilthemathguy** [comment]
Could you create an issue and  provide specific details? I am closed this thread because of generic description. Thanks!

**Comment by namchester** [comment]
sorry

On 25 May 2015 at 19:24, neilthemathguy <notifications@github.com> wrote:

> Could you create an issue and provide specific details? I am closed this
> thread because of generic description. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crowdresearch/crowdsource-platform/issues/115#issuecomment-105238107>
> .
>



-- 
Naman Gupta,
B.Tech 2013
IIIT-Delhi
Contact: 8860354494 | naman13064@iiitd.ac.in
