### ISSUE TITLE
Route backend errors to frontend

### ISSUE THREAD

**Issue by shirishgoyal** [crowdresearch/crowdsource-platform#121]
**Issue**
Registration form (and forms in general) are not showing the validation or other backend errors on the frontend. Instead it shows a generic error without much detail on what the error is.

**Suggested Solution**
Implement an angular directive(s) to show field level errors as well as show form level errors.
Implement backend changes to pass the errors back in HTTP response.

**Comment by neilthemathguy** [comment]
Could you add appropriate labels? 

Thank you.

**Comment by mbernst** [comment]
Subscribing, I encountered this with a < 8 character password

**Comment by dmorina** [comment]
done
