### ISSUE TITLE
contact Us Form (Nice to Have)

### ISSUE THREAD

**Issue by Kevinle45** [crowdresearch/crowdsource-platform#137]
Create a Contact us link between Follow Us and search
![screen shot 2015-05-25 at 7 42 52 pm](https://cloud.githubusercontent.com/assets/12235394/7805298/8e7b43fe-0324-11e5-99b1-3d4e4545ccd4.png)

**Comment by MisterCruz** [comment]
Added contact us to nav bar

**Comment by MisterCruz** [comment]
I signed the CLA.
