### ISSUE TITLE
Implement AngularJS UI Grid

### ISSUE THREAD

**Issue by maniksingh92** [crowdresearch/crowdsource-platform#19]
The AngularJS team is working on http://ui-grid.info/ which is a Native AngularJS implementation, no JQuery dependency. The project is still beta but will officially replace ng-grid sometime in the future.

Upgrade from ng-grid 2.x to ui-grid 3.0
http://ui-grid.info/docs/#/tutorial/099_upgrading_from_2

**Comment by neilthemathguy** [comment]
Yes we are not moving toward ng-grid. We are replacing it with smart-table.
