### ISSUE TITLE
Refine UI Authentication

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#22]
* Enhancement of the front end login/authentication experience across all the pages. 
* Adding the http headers to front end; pass the OAuth2 authorization (token) in the header.

**Comment by nistala** [comment]
There is a dependency problem with this from the backend. @dmorina I am seeing this error from the backend whenever I log in: {'message': 'OK', 'error_description': 'Invalid credentials given.', 'error': 'invalid_grant'}, these are the params I am passing in (replaced password): username=asdf%40asdf.com&client_secret=z7pmA2L40fRYhfhrrrx69c7RDaHY4GcjCUfppPWZLMPbhn2L5KICiKQXyP4Drf4sbN4wbPFuybbq2nJuCA3x1Pf1j2ZuBVZB48bFwexagcuQvB3D6I80xiwKsM9TmDel&password=<password>&client_id=3NegWyU7oyN0TAOM04mflVPNBhciZKJbAzuPQbsS&grant_type=password

**Comment by dmorina** [comment]
There shouldn't be any issues with this, please make sure you have updated your database correctly. Report back if issue persists

**Comment by dmorina** [comment]
issue resolved, after authentication username will be passed to the oauth2 endpoint
