### ISSUE TITLE
Analytics & Machine Learning capabilities

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#23]
* Build analytics infrastructure with ml libraries and algorithms
* Create dummy datasets and map it to existing models.
* Incorporate D3 for visualization

**Comment by YenHuang** [comment]
Me and @jorghi12 have built models, what features to keep track of, and dummy datasets. Our explanation of our thought process can be seen here 

https://docs.google.com/document/d/1mHkQBZrRQH61vepvipICQ0fOgMonVROPrx2v5q1zKmY/edit?usp=sharing
