### ISSUE TITLE
Task Monitoring: convergence and HTML prototypeing

### ISSUE THREAD

**Issue by ryosuzuki** [crowdresearch/crowdsource-platform#252]
There are two parts to this milestone. First, work with folks in #micro-macro to synthesize these designs and, as a group, come up with a mockup that represents your collective opinion on how this should work.

Second, create an HTML interface that translates these ideas into an HTML page. We prefer if you use the CSS templates from our github repository, check with folks in #research-engineering if you'd like help. Show how this would work with both a microtask such as webpage classification (e.g., is this web page a restaurant homepage, or not?) and with a macrotask such as copyediting an essay. The page can be static, but it should be a faithful mockup of the proposal.

**Comment by neilthemathguy** [comment]
Not sure what is the purpose of this
