### ISSUE TITLE
Task Search

### ISSUE THREAD

**Issue by kunal15595** [crowdresearch/crowdsource-platform#26]
Link - http://127.0.0.1:8000/tasklistSearch
Task search is not working properly.
Problem - Search results contain unrelated tasks.
Instances:
1. Full text - `tagging`
2. Partial text - `im`

**Comment by neilthemathguy** [comment]
Could you provide further details? 
What term did you enter in the search box? The search will match the labels in all the column depending on the term you enter. For examples, if you search for writing it will show you all the tasks that contain word writing.

**Comment by swapagarwal** [comment]
"tagging" keyword is not there in 2nd result.
![selection_001](https://cloud.githubusercontent.com/assets/2833845/7499057/e0e6d432-f442-11e4-9fe1-42e62b940a60.png)
"im" is not there in 3rd result.
![selection_002](https://cloud.githubusercontent.com/assets/2833845/7499137/4620b4da-f443-11e4-94e4-807aa09d518c.png)

**Comment by neilthemathguy** [comment]
Oh okay. So the current search functionality coverse entire universe in the table. That's why for im you are seeing all the tasks that has im* in it. As we add more features we will narrow it down to specific columns. In current context it is displaying the correct data.

**Comment by swapagarwal** [comment]
Where does im* match in 3rd result?

**Comment by neilthemathguy** [comment]
I will take a look at it once I reach to machine. I will try to replicate what you see.

**Comment by neilthemathguy** [comment]
Good catch. Fixed!
