### ISSUE TITLE
Provision Django with Gunicorn and Nginx.

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#36]
@dmorina @nistala @neilthemathguy

**Comment by nistala** [comment]
We can set this up, let's pick a branch and set development environment: https://devcenter.heroku.com/articles/github-integration

**Comment by neilthemathguy** [comment]
@nistala Sounds great!

**Comment by neilthemathguy** [comment]
About Travis CI let's go for it!
