### ISSUE TITLE
unminifying angular JS

### ISSUE THREAD

**Issue by kunal15595** [crowdresearch/crowdsource-platform#4]
Absence of angular JS map files:
1. angular.min.js.map - https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.min.js.map
2. angular-route.min.js.map - https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular-route.min.js.map
3. angular-cookies.min.js.map - https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular-cookies.min.js.map

Please add these to *staticfiles/angular/*

**Comment by dmorina** [comment]
We are moving to bower, that will take care of this
Thanks
