### ISSUE TITLE
Lock down the registration  

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#409]
1. Lock down the registration form so that we prevent random folks signing up and creating the account to attempt the task. We will need to run in the closed beta environment.  
2. We will register the worker in the system, create an account for them.  
3. The workers can change the password once they login.

**Comment by neilthemathguy** [comment]
#411

**Comment by dmorina** [comment]
there exists a flag in settings.py `REGISTRATION_ALLOWED` which handles this

**Comment by maniksingh92** [comment]
is locking down necessary, or are we good to go with the email verification system implemented by @dmorina #449 ?

**Comment by dmorina** [comment]
It will be necessary. We will allow only few people to sign up

**Comment by dmorina** [comment]
@aginzberg is assigned
