### ISSUE TITLE
Static Content Hosting

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#43]
1. Register to Amazon S3 free tier or dropbox to host the static content  
2. Migrate the current code to reference the new location 

___________________________________________________________________________________
### Assigned 

GROUP 1

GROUP 2
___________________________________________________________________________________
### DRI
@neilthemathguy  @dmorina @nistala

**Comment by nistala** [comment]
@neilthemathguy Could we serve content from heroku for now? Since we only have images, gunicorn/nginx should work well enough and we can host videos on youtube.
Ask - remove 0.Open&Critical label.

**Comment by neilthemathguy** [comment]
Sounds good we can do that. Let's have a backup plan to move away from heroku in longer run. 
Ask- Done

**Comment by dmorina** [comment]
I think this would be a cool feature for the users to be able to connect their cloud accounts to our platform there are different use cases

**Comment by dmorina** [comment]
As for the static files used by the frontend I think they should say local to the web server, otherwise if these services are down for whatever reason our web will not work

**Comment by dmorina** [comment]
stay* :P
