### ISSUE TITLE
Change password does not show error messages when bad request

### ISSUE THREAD

**Issue by nistala** [crowdresearch/crowdsource-platform#438]
Error reporting broken for change password.
Steps to replicate:

Enter incorrect old password
enter new password
enter matching new password 2

submit

**Comment by dmorina** [comment]
![screen shot 2015-08-28 at 07 05 47](https://cloud.githubusercontent.com/assets/2858281/9539551/457cbb32-4d53-11e5-804a-4132f599ba98.png)

**Comment by dmorina** [comment]
are you sure about this one?
cannot reproduce

**Comment by neilthemathguy** [comment]
Looks good to me. Can someone confirm.

**Comment by aginzberg** [comment]
yes works for me.

**Comment by aginzberg** [comment]
can we close this?

**Comment by dmorina** [comment]
I think so

**Comment by neilthemathguy** [comment]
lgtm++ @nistala are you still facing this issue?

**Comment by nistala** [comment]
try a smaller password

**Comment by nistala** [comment]
![screenshot from 2015-08-28 11 52 32](https://cloud.githubusercontent.com/assets/4357428/9554542/64abe6c2-4d7b-11e5-9d03-fb22ffbc598c.png)

**Comment by aginzberg** [comment]
good catch

**Comment by dmorina** [comment]
resolved
