### ISSUE TITLE
Link change password

### ISSUE THREAD

**Issue by nistala** [crowdresearch/crowdsource-platform#439]
Currently unlinked, cannot be reached.

**Comment by shirishgoyal** [comment]
This part is working correctly. 
Link works and mail received.
Mail has link which connects correctly to reset form and password is correctly reset.

**Comment by mbernst** [comment]
If confirmed, we can close this?

**Comment by dmorina** [comment]
we need to add the Button/Link next to Logout (tiny thing)
just does an href to /change-password

**Comment by shirishgoyal** [comment]
Resolved in https://github.com/crowdresearch/crowdsource-platform/issues/439
