### ISSUE TITLE
Registration 

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#44]
### Events that will trigger the registration process: 
> 1. A random surfer visits the home page
> 2. The random surfer clicks on Worker Registration or Requester Registration 
> 3. The Registration starts now 

Be creative and enhance the suggested workflow to make it better 
___________________________________________________________________________________
### If the random surfer is a Worker
**Form 1: Personal Information** 

HEADER Highlight the Two Step Registration process  
> 1. Thumbnail for PERSONAL INFORMATION (ACTIVE)
> 2. Thumbnail for SKILLS (FROZEN)

Add the Form Content
> 1. Country of Residence 
> 2. First Name
> 3. Last Name
> 4. Email
> 5. Password
> 6. Confirm Password
> 7. Phone Number
> 8. Click Next

**The worker clicks NEXT**

**Form 2: Skill Information**
HEADER Highlight Two Step Registration process  
> 1. Thumbnail for PERSONAL INFORMATION (DONE)
> 2. Thumbnail for SKILLS (ACTIVE)

Add the Form Content
> 1. Address 
> 2. City 
> 3. Zip Code
> 4. Add SSN or Tax Identifier Number (make it optional for now)
> 5. Select Skills (from dropdown)
> 6. Select three location from where the HITs will be performed 
> 7. Add social networking profiles (optional) Linkedin/oDesk/MTurk profile
> 8. Sign UP Button

___________________________________________________________________________________

### If the random surfer is a Requestor
**Form 1: Personal Information** 

HEADER Highlight the Two Step Registration process  
> 1. Thumbnail for PERSONAL INFORMATION (ACTIVE)
> 2. Thumbnail for SKILLS (FROZEN)

Add the Form Content
> 1. Country of Residence 
> 2. First Name
> 3. Last Name
> 4. Email
> 5. Password
> 6. Confirm Password
> 7. Phone Number
> 8. Click Next

**Form 2: Skill Information**
HEADER Highlight Two Step Registration process  
> 1. Thumbnail for PERSONAL INFORMATION (Check Box DONE)
> 2. Thumbnail for SKILLS (ACTIVE)

Add the Form Content
> 1. Address 
> 2. City 
> 3. Zip Code
> 4. Add SSN or Tax Identifier Number (make it optional for now)
> 5. Select Skills (from dropdown)
> 6. Select three location from where the HITs will be performed 
> 7. Add social networking profiles (optional) Linkedin/oDesk/MTurk profile
> 8. Sign UP Button

___________________________________________________________________________________
### Folders to look at
view: `templates/authentication` 
js: `authentication (LoginController and RegisterController)` 
routes: `crowdsource.routes.js`
___________________________________________________________________________________
### Assigned 

GROUP 1
@aditimithal @rushj22 @namchester   

GROUP 2
@phiju123 

___________________________________________________________________________________
### DRI
@neilthemathguy  @dmorina @nistala

**Comment by phiju123** [comment]
Can i do this??

**Comment by nistala** [comment]
@aditimithal there are a lot of temporary files (ending with ~), could you please remove them?

**Comment by neilthemathguy** [comment]
@phiju123 added you to the group 2.

**Comment by uwecerron** [comment]
why are ssn's required for the worker? will they be employees of the platform or contractors?
