### ISSUE TITLE
Task Submission Workflow 

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#441]
After task submission or ending the HITs:  Add either confirmation or redirect to the central profile page that gives worker a snapshot/summary of the current state  (https://github.com/crowdresearch/crowdsource-platform/issues/48)  

User story: (reported by @rahulrocks1016) 
> I attempted a hit request put out by @neilthemathguy
> Dashboard interface was perfect. I was able to initially access the tasks in task feed with ease. After I accessed the tasks in task feed, I was also able to work on them for the first time
> After you submit a task, it brings you to a blank page. Ideally, there should be another designated page that this goes to.                                    
> I visited the task feed page, the actual "work-on-task" page, the post submission blank page, and the dashboard.

**Comment by nistala** [comment]
after the task is done, we could direct them to the dashboard and show tasks in review.

**Comment by shirishgoyal** [comment]
Cannot replicate this issue anymore. On submission, user is shifted to dashboard.
