### ISSUE TITLE
Task state: could not resume/access the task after saving 

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#442]
The user could not resume/access the task after saving it.  (reported by @rahulrocks1016) 

User story: 
> I attempted a hit request put out by @neilthemathguy
> Dashboard interface was perfect. I was able to initially access the tasks in task feed with ease. After I accessed the tasks in task feed, I was also able to work on them for the first time
> I could not access my tasks after I saved them. Although I could see that they were in progress on the Dashboard, I could not go back to work on them. Also, the tasks disappeared from the task feed.
> I visited the task feed page, the actual "work-on-task" page, the post submission blank page, and the dashboard.

**Comment by aginzberg** [comment]
This is possible by going to the dashboard and clicking to finish the corresponding in progress task. Do people have ideas for how we could make this more user friendly?

**Comment by neilthemathguy** [comment]
I will add the workflow by tonight, feel free to comment on it. One possible solution I see is providing the summary of in progress/ completed tasks in the person; dashboard page.
