### ISSUE TITLE
Task Refresh/Realtime updates

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#444]
User Story (reported by Jsilver) 
>I noticed some tasks appeared after reloading the page for the 2nd or 3rd time (i was logging out at that time). i logged in again. in the task feed tab, the "No free tasks available" message is still shown (for a second) before the task feed appears. 

I am trying to replicate this.

**Comment by dmorina** [comment]
That can happen if tasks are unavailable we will check this

**Comment by maniksingh92** [comment]
I think the asynchronous nature of the http service explains "the No free tasks available message is still shown (for a second)". It has happened with me also. Once getProjects() returns data into taskfeed.availableTasks, the "no free tasks available" message gets hidden and replaced by the list of tasks

**Comment by shirishgoyal** [comment]
Resolved

**Comment by mbernst** [comment]
@shirishgoyal please link to the PR that resolved this?

**Comment by shirishgoyal** [comment]
https://github.com/crowdresearch/crowdsource-platform/pull/469

**Comment by mbernst** [comment]
Thanks!

**Comment by shirishgoyal** [comment]
For real-time updates without refresh, we will need to add websocket support.

**Comment by neilthemathguy** [comment]
@shirishgoyal yes: #57
