### ISSUE TITLE
Navigation Bar 

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#445]
This will be moved to the top soon. We will need to start working on overall interaction design part soon. 

> User story (jsilver) 
The width of the tab area (from My Account to Logout) could be cut by 60%, so the taskfeed and task pages/details could have more room.

**Comment by shirishgoyal** [comment]
Improved layout in https://github.com/crowdresearch/crowdsource-platform/pull/477
