### ISSUE TITLE
Ratings UI for workers to rate requesters

### ISSUE THREAD

**Issue by nistala** [crowdresearch/crowdsource-platform#447]
Rating UI for workers to rate requesters

**Comment by maniksingh92** [comment]
I can work on the frontend UI and logic, someone wants to pair up for the backend logic?

**Comment by dmorina** [comment]
talk to @nistala about this, he's already working on it, I can assist you guys on the backend

**Comment by nistala** [comment]
![requester to worker](https://cloud.githubusercontent.com/assets/4357428/9563476/d511ca1c-4e39-11e5-8ddd-a1af03d72840.png)
![worker-requester](https://cloud.githubusercontent.com/assets/4357428/9563477/d6ae320c-4e39-11e5-891f-c0ad37246d54.png)

**Comment by nistala** [comment]
Design and API - http://crowdresearch.stanford.edu/w/index.php?title=Reputation_and_ranking#API
