### ISSUE TITLE
Enhance Font Awesome Icons

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#45]
In addition to the [font-awesome icons](http://fortawesome.github.io/Font-Awesome/icons/), we will need to create/or enhanced Icons. 

> 1. Make a list of all the icons we will need for the platform
> 2. Check if the icons are available in the font-awesome library, if not create new one or derive from open source work (make sure to check appropriate license)
> 2. Define the image resolution and size. [Example](http://fortawesome.github.io/Font-Awesome/examples/)  

Update following list with new icons, upload the icon image to wiki and add the respective link here. 
> 1. Worker
> 2. Requester
> 3. Payment 
> 4. 
> 5. 

___________________________________________________________________________________
### Folders to look at
`staticfiles/css`
`staticfiles/images`
___________________________________________________________________________________
### Assigned 

GROUP 1

___________________________________________________________________________________
### DRI
@neilthemathguy

**Comment by webmaven** [comment]
@dmorina Was this done?

**Comment by dmorina** [comment]
we are not using them anymore

**Comment by mbernst** [comment]
@webmaven are you joining our project?

On Sunday, November 22, 2015, Durim Morina <notifications@github.com> wrote:

> we are not using them anymore
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crowdresearch/crowdsource-platform/issues/45#issuecomment-158814126>
> .
>


-- 
sent from my NLS

**Comment by webmaven** [comment]
@mbernst, I *may* be looking for places I can contribute on this project. Right now I just started looking for some low-hanging fruit, unless you want to make a job offer of some sort. :innocent:
