### ISSUE TITLE
fix data source on Design Tab

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/crowdsource-platform#450]
after selecting a data source for a particular item the Data Source field appears as filled for any other item after that (even though it isnt)
we need to reset that if data source is null and change it if it already exists

**Comment by maniksingh92** [comment]
Working on it. it's probably because i used $scope models for the autocomplete, so that's why the textual info is shared across the placeholder of the autocomplete of each element property

**Comment by maniksingh92** [comment]
fixed. will test and PR soon

**Comment by maniksingh92** [comment]
i think this issue can be safely closed

**Comment by dmorina** [comment]
yeah if pr is merged we can close it
