### ISSUE TITLE
Task design data is persisted

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#453]
Task design data is persisted after creating the project. 

1) Create a project; for instance label the images 
2) Visit the workflow to create second project let's say translate the doc- I still see the content of first one in the forms; rather than blank forms

**Comment by maniksingh92** [comment]
this issue can be replicated even without creating a project. simply choose to create a project and type in info, create the task template etc and navigate to any other link on the page. then try to "create project" again, and the data remains.

**Comment by shirishgoyal** [comment]
Resolved in https://github.com/crowdresearch/crowdsource-platform/pull/486
