### ISSUE TITLE
Rating Interface Refresh 

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#473]
Rating interface refreshes each time a user clicks the new rating. Try multiple requesters.

**Comment by shirishgoyal** [comment]
Is this refresh kept to account for rating happening across the application ?

**Comment by dmorina** [comment]
@shirishgoyal not really, it shouldnt refresh at all just update the object on success and extend it with an ID

**Comment by mbernst** [comment]
Yeah, if others are rating simultaneously, it wouldn't affect the user
experience to wait until a reload before it shows up.

**Comment by dmorina** [comment]
@mbernst the thing is that this is a list of requesters rated by `this` worker, so no one else can do your ratings, no refresh is needed
