### ISSUE TITLE
Issues with Task Feed on Dashboard

### ISSUE THREAD

**Issue by shirishgoyal** [crowdresearch/crowdsource-platform#479]
a) When there is no Task in Progress, once we select checkbox for all, we cannot deselect it

b) On selecting any task in Returned Tasks, it shows action buttons on Task in Progress section rather than Returned Tasks Section. See image below for reference.

![image](https://cloud.githubusercontent.com/assets/315012/9625955/a001a8ce-5177-11e5-957a-69c4e6c94efb.png)

**Comment by dmorina** [comment]
A) has been addressed 
I agree b) should be like you described it

**Comment by aginzberg** [comment]
regarding a. i think we should disable (or modify) the select all checkbox (like on github) when people start selecting individual tasks. we get some really weird behavior when you start selecting individual individual tasks and then start toggling the select all checkbox.

**Comment by lucamatsumoto** [comment]
I found two "md-data-table" implementations and both work in the same way when you select check-all after selecting some individual rows. Demo sites; http://danielnagy.me/md-data-table/ http://iamisti.github.io/md-data-table/ We can implement the same behavior quickly if that is what we wanted. And we should do the same for the task overview.

**Comment by shirishgoyal** [comment]
In progress

**Comment by shirishgoyal** [comment]
Resolved a) which appears natural in function now,
and b)

**Comment by shirishgoyal** [comment]
Resolved
b) Returned tasks maintain their separate queue. On save, task gets merged to task in progress list. 
Actions shown separately for Returned tasks which do not interfere with Task in progress queue.
