### ISSUE TITLE
daemo.stanford.edu issues with CSRF

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/crowdsource-platform#497]
{"detail":"CSRF Failed: Referer checking failed - https://daemo.stanford.edu/profile does not match https
://daemo.herokuapp.com/."}

When I try to logout from daemo.stanford.edu
this happens because of the domain mismatch in the csrf token

**Comment by shirishgoyal** [comment]
Resolved in #507 

CSRF middleware can be reverted to normal once domain redirection is corrected.

**Comment by shirishgoyal** [comment]
Domains added to check CSRF referrer against.
