### ISSUE TITLE
Check status message on account activation

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/crowdsource-platform#504]
Couple of users reported that they see "Invalid activation key" on the first time they try to activate it.
Could be that they refreshed the page, anyway we should check and improve this message (in case it's activated "Account successfully activate"

**Comment by shirishgoyal** [comment]
There is no reference to user available as activation key is removed during first call. So we cannot check if the account is active or not on subsequent calls.

**Comment by dmorina** [comment]
they claim it happens on the first call, can we check that if we have a problem (normally not)

**Comment by shirishgoyal** [comment]
Checked for first call and there appears no issue. On subsequent calls, shows "Invalid activation key" which looks to be correct.

**Comment by dmorina** [comment]
few users claim that it happens on the first call

**Comment by shirishgoyal** [comment]
#540
