### ISSUE TITLE
Worker Experiment: Capture the rating above the comment box

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#508]
Ask workers rate requesters while attempting the task. Add rating check minus, check, check plus above the comment box.

**Comment by mbernst** [comment]
Let me know if you'd like a design sketch

**Comment by shirishgoyal** [comment]
Will worker be rating requester per task or per milestone ? 
Currently it is per milestone.

**Comment by mbernst** [comment]
Per milestone, yes. If I rate someone in one task, the rating should
"stick" while I do additional tasks in the batch.

**Comment by dmorina** [comment]
that already exists, we just have to continue with FE
