### ISSUE TITLE
Unsupported browsers and other checks

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/crowdsource-platform#509]
We should mark IE as an unsupported browser (anyone who would like to provide support be my guest :D)
Show the notification page which tells them to get a real browser
Check if cookies and js are enabled, as our app is based on them we should show a message to enable them if they want to continue using our platform

Others to be added if any

**Comment by Curious72** [comment]
@dmorina So we need to just check if Daemo works properly on different browsers?

**Comment by dmorina** [comment]
yea

**Comment by insomniac12** [comment]
@dmorina I am using browsershots for checking this issue. Can you please tell me what all browsers I need to check and also what files should I upload?

**Comment by dmorina** [comment]
well we check when user opens page what browser they are using and warn them for unsupported ones or if they have disabled JS or cookies
