### ISSUE TITLE
Task submission enhancements 

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/crowdsource-platform#511]
Two buttons {Submit, Skip} and a switch which says "Accept next task automatically"

this has to be stored a user preference

**Comment by dmorina** [comment]
two default buttons the rest should go under More (horizontal or vertical more icon with drop down menu would be an idea)

**Comment by dmorina** [comment]
add timer, in case timer has expired let the worker know that this task may be revoked from him in case someone else wants to attempt this task

**Comment by shirishgoyal** [comment]
#498 can be closed as it captured the same problem
