### ISSUE TITLE
Image container field not showing image

### ISSUE THREAD

**Issue by nistala** [crowdresearch/crowdsource-platform#513]
Steps to reproduce:

- Create a project
- Create a dummy prototype task
- Create a new milestone
- In the design page create an image container field - enter the following image url: http://sports.cbsimg.net/images/blogs/Gio-Bernard-Panthers-TD-321.png
- Login as another user and attempt task, the image will not render.

**Comment by dmorina** [comment]
that's because the material-design-icons are missing in bower.json

**Comment by shirishgoyal** [comment]
Resolved in https://github.com/crowdresearch/crowdsource-platform/pull/514

**Comment by shirishgoyal** [comment]
Option field - for showing static image using URL
Data Source - for providing dynamic input for image as URL

**Comment by dmorina** [comment]
perfect
