### ISSUE TITLE
Task preview does not fill in data from CSV

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#516]
Make a task with inputs from the CSV. The preview doesn't show them.

<img width="892" alt="screen shot 2015-09-11 at 9 53 43 pm" src="https://cloud.githubusercontent.com/assets/249285/9829929/997dcf0a-58cf-11e5-99f3-ca44d179aa6b.png">

Leads to a preview that doesn't fill in from the CSV:
<img width="1275" alt="screen shot 2015-09-11 at 9 54 09 pm" src="https://cloud.githubusercontent.com/assets/249285/9829930/a6d93536-58cf-11e5-9138-0d922b8ab536.png">

**Comment by dmorina** [comment]
Will take care of it
