### ISSUE TITLE
Task template is showing items in quite a different order than what requester posted

### ISSUE THREAD

**Issue by shirishgoyal** [crowdresearch/crowdsource-platform#528]
![image](https://cloud.githubusercontent.com/assets/315012/9835147/cffcea14-59f8-11e5-9b6a-7ab760641c76.png)

This template shows items in a different order than posted. Description is showing at end while it was the first item added.

**Comment by dmorina** [comment]
are you sure about this one? it's an issue we had fixed some time ago @aginzberg 
cannot reproduce

**Comment by dmorina** [comment]
tested and it works well, not sure how this project was created item positions are wrong 
label,"You will be given a site name, find the domain URL for that site.

4
4
3
4
2
4

**Comment by shirishgoyal** [comment]
Resolved in https://github.com/crowdresearch/crowdsource-platform/pull/532
