### ISSUE TITLE
Worker Profile: Acceptance Test

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#54]
___________________________________________________________________________________

### Task  
> 1. Based on the current worker's profile create user stories and translate them into the functional test requirements. At present, once a worker visits the profile page, he get information about his personal data, skills, summary of tasks, status of task, and payments. 
> 1. Write functional test describing the profile functionality from the worker's point of view. 
> 2. Include all assertions related to the worker profile. 
> 3. Add functional tests under `crowdsourcing/tests/`
>4. You may need to setup external packages to integrate test cases with [Travis CI](https://travis-ci.org/crowdresearch/crowdsource-platform/) 

___________________________________________________________________________________

### Technologies 
Information Flow: Storyboard, Power Point or Keynote
Tests: Python, Travis-CI, Selenium browser automation tool  
___________________________________________________________________________________

### Assigned 
GROUP 1
 
GROUP 2   

___________________________________________________________________________________
### DRI
@neilthemathguy @dmorina @nistala  

___________________________________________________________________________________

### Related Issues
>1. Acceptance Test #54
>2. HTML, CSS, Bootstrap #48	
>3. Angular JS  #50	
>4. Rest API Data Models #51	
>5. Automated Testing #56 

___________________________________________________________________________________

### References & helpful books

[Test Driven Python](http://chimera.labs.oreilly.com/books/1234000000754/ch01.html)
 
___________________________________________________________________________________

### Current Profile Page 

![Design Reference]
(http://crowdresearch.stanford.edu/w/img_auth.php/8/83/Workerdashboard.png)

**Comment by PabitraPati** [comment]
I want to take this task up. But for proceeding ahead, I need mockups or UI screenshots for reference. Where can I find those ???

**Comment by Gematb** [comment]
I'm interesting about the worker profile, specially in the second point but I have some questions about the test? Have an example?

**Comment by neilthemathguy** [comment]
Please take a look at the References & helpful books highlighted in the task description. Thank you

**Comment by neilthemathguy** [comment]
@Gematb please take a look at the References & helpful books highlighted in the task description. Thank you. Requirements for the task board are being discussed on the slack channel, so please feel free to join. worker-profile

**Comment by neilthemathguy** [comment]
@PabitraPati the UI screenshot is listed in the above task description, you can also access it by setting up the local environment.
