### ISSUE TITLE
CSV patches: Sort CSV results by task_id, fix download

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#558]
-Easiest to understand overall quality if the results are grouped by task, rather than by worker. That way the user can skim to see how much people agree, and what inputs are causing trouble
-make sure the csv is always able to be downloaded, e.g handle the case when no results are available

**Comment by dmorina** [comment]
Agreed

**Comment by Curious72** [comment]
@mbernst Can you explain exactly what is to be done?

**Comment by mbernst** [comment]
Sure. When the user downloads a task results CSV, we apply a primary sort key of the Task ID before returning it to them. Right now I think it's sorted by submission time.

With handling an empty CSV, I don't recall the bug, it may have been that things errored if you tried to download the CSV but there were no results yet.

**Comment by qwertyone** [comment]
There needs to be a human identifier -- some way for a requester to name
the columns rather than it coming out as "Option 1", "Option 2"... "Option
N".
