### ISSUE TITLE
Smart Table Migration: angular

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#58]
## Enhance the use of smart table and search across multiple pages  
> 1. Migrate ng-grid modules to smart table
> 2. Decommission ng-grid
> 3. Targeted pages/tables: Task, Workers, Requesters, Rankings 
> 4. Add pagination
> 5. Provide support to other pages where smart-table will be useful to add

___________________________________________________________________________________
### Assigned 
GROUP 1
@neilthemathguy @Soroosh129 @srxzr @nistala 

___________________________________________________________________________________
### Related 
#20
___________________________________________________________________________________
### DRI
@neilthemathguy @nistala @dmorina

**Comment by nistala** [comment]
Beginning work for removing ng-grid and using smart table - https://github.com/crowdresearch/crowdsource-platform/pull/70
