### ISSUE TITLE
add iframe component

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/crowdsource-platform#596]
- add iframe component to the template designer

```
-it should be treated as other template items with its own properties; probably an hstore here would be the best solution
-sandbox it: allow-forms, allow-same-origin and allow-scripts
-we would like to allow to POST the data back to us that is the *action* attribute to be a url like https://daemo…./api/task/external-submit ; no login info will be provided
you will have to loop few parameters to identify the worker and the task 
```

**Comment by shirishgoyal** [comment]
#604 - covers the frontend piece (will need changes based on backend discussion)

Also we cannot alter data on iframe part (modifying "action" for form), so we need to leave instructions for author to use parameters passed in URL and pass back to platform.

We need more discussion on how we wire the backend as it also connects with how author reviews the completed task - data linked to iframe (only if it has some form based or input content).

**Comment by dmorina** [comment]
if they allow cross domain then Yes you can alter (or proxy) but we dont need it if we pass params

**Comment by shirishgoyal** [comment]
Agreed. We need a design which always works and URL params seems to be solution but we need to depend on how authors use it on their end.
