### ISSUE TITLE
Worker Portfolio: Data model and REST API

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#61]
___________________________________________________________________________________

### Task
> 1. Enhance existing data model to support a Worker's task dashboard 
> 2. Build REST API, view sets to support the task dashboard
> 4.  At present, once a worker visits the task portfolio page, he get information about the tasks he has carried out. Tasks have ratings and reviews associated with it. This page can be public i.e. available to other workers and requesters.

___________________________________________________________________________________

### Technologies 
Python, Django Framework, REST API, PostgreSQL, Understanding of ORM 
___________________________________________________________________________________

### Related Issues
>1. Acceptance Test #63
>2. HTML, CSS, Bootstrap #59 
>3. Angular JS  #60 
>4. Rest API Data Models #61    	
>5. Automated Testing #62   

___________________________________________________________________________________

### Assigned 
GROUP 1
 @uwecerron @neilthemathguy
GROUP 2

___________________________________________________________________________________
### DRI
@dmorina  @elsabakiu  @neilthemathguy 
___________________________________________________________________________________

### Files
`crowdsourcing/models.py`
`crowdsourcing/serializers/worker.py`
`crowdsourcing/viewsets/worker.py`
`crowdsourcing/views.py`
`crowdsourcing/csp/urls.py`
`crowdsourcing/fixtures/`

___________________________________________________________________________________
### Reference
Below is an example of required information. This will change and evolve as we progress. Therefore, be creative and add further enhancements. Also check related issues to satisfy front end requirements

![Design Reference]
(http://crowdresearch.stanford.edu/w/img_auth.php/b/bf/Task_portfolio.png)

![Design Reference]
(http://crowdresearch.stanford.edu/w/img_auth.php/2/26/Data_Model_600_300ppi.jpg)

**Comment by uwecerron** [comment]
is anyone working on this?

**Comment by neilthemathguy** [comment]
At present no, would you like to pick this up?

**Comment by uwecerron** [comment]
yes, I will then.

**Comment by neilthemathguy** [comment]
Thank you added you to the Group1 who will work on this task. In case you need any help please feel free to reach out to DRIs. We can add more people to this issue as we progress.

**Comment by uwecerron** [comment]
understood
