### ISSUE TITLE
Number of workers validation isn't working

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#610]
I entered a task with 100 replication. Then for the prototype reduced it to four. Got this:
<img width="1062" alt="screen shot 2015-12-23 at 3 58 56 pm" src="https://cloud.githubusercontent.com/assets/249285/11987100/25a48b40-a98e-11e5-9fe6-b9e3634753a8.png">

**Comment by mbernst** [comment]
Oh it seems to be boxed into [1,3]? If that's the desired behavior, we should auto-round it down to 3 and give a message that says prototype tasks only go up to 3 workers.

**Comment by dmorina** [comment]
@aginzberg ?

**Comment by dmorina** [comment]
confirmed there is a min="1" and max="3"
