### ISSUE TITLE
White tab highlight in navbar

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#612]
This tab highlight is red, but should probably be white:
<img width="105" alt="screen shot 2015-12-23 at 6 00 51 pm" src="https://cloud.githubusercontent.com/assets/249285/11988105/2c34fe0c-a99f-11e5-8c55-5a1391f982f8.png">

**Comment by dmorina** [comment]
Spec says: 
Indicator
    Height: 2dp
    Color: #fff or accent color

I think Chris chose this as accent on those regions we can change it to white too

**Comment by mbernst** [comment]
This might be a broader design discussion, but the purple is so dominant
that I'm inclined to make the purple the accent color. So when you want an
accent that's on a purple field, we'd have to use white.

**Comment by dmorina** [comment]
<img width="1810" alt="screen shot 2015-12-01 at 12 23 41 am" src="https://cloud.githubusercontent.com/assets/2858281/11988169/1d6758f6-a9a0-11e5-9903-96128bebb349.png">
this was the original gradient

**Comment by dmorina** [comment]
<img width="1432" alt="screen shot 2015-12-23 at 6 10 49 pm" src="https://cloud.githubusercontent.com/assets/2858281/11988191/9825dc70-a9a0-11e5-9e4f-0dec10859461.png">
this is how it would look like in white

**Comment by mbernst** [comment]
I like the white.

On Wednesday, December 23, 2015, Durim Morina <notifications@github.com>
wrote:

> [image: screen shot 2015-12-23 at 6 10 49 pm]
> <https://cloud.githubusercontent.com/assets/2858281/11988191/9825dc70-a9a0-11e5-9e4f-0dec10859461.png>
> this is how it would look like in white
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crowdresearch/crowdsource-platform/issues/612#issuecomment-167024806>
> .
>


-- 
sent from my NLS
