### ISSUE TITLE
Vagrant up fails while executing pip install requirements.txt

### ISSUE THREAD

**Issue by thunderboltsid** [crowdresearch/crowdsource-platform#625]
When the provision script reaches "sudo pip install -r requirements.txt" and tries installing cffi, it terminates with the following error: 

"i686-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-i686-2.7/c/_cffi_backend.o
c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
                 ^
compilation terminated.
error: command 'i686-linux-gnu-gcc' failed with exit status 1"

This in general is an issue when I ssh'ed into vagrant instance and did "pip install cffi". Building cffi from source gives the same error. What are we using cffi for?

**Comment by dmorina** [comment]
We will fix the scripts, for now try installing libffi-dev using apt-get
One of the other  requirements uses it

**Comment by thunderboltsid** [comment]
Yeah, that fixes it. Will do a pull request with that added.
