### ISSUE TITLE
Migration 0000_hstore fails during vagrant up

### ISSUE THREAD

**Issue by thunderboltsid** [crowdresearch/crowdsource-platform#628]
The error says:
==> default: django.db.utils.ProgrammingError: permission denied to create extension "hstore"
==> default: HINT:  Must be superuser to create this extension.

And, ofc, while running this with sudo, it results in
django.db.utils.OperationalError: FATAL:  role "root" does not exist

find the screenshots of the terminal attached.
![screen shot 2016-01-12 at 7 35 00 am](https://cloud.githubusercontent.com/assets/6081171/12256995/aa7f9aca-b902-11e5-99f9-980a9a21fec7.png)
![screen shot 2016-01-12 at 7 35 45 am](https://cloud.githubusercontent.com/assets/6081171/12257000/b2ad44d6-b902-11e5-87ec-6edb15b7b551.png)

**Comment by dmorina** [comment]
That means that you should run the create hstore using a db superuser

**Comment by dmorina** [comment]
Or grant that privilege to whatever user you are trying to run it with
