### ISSUE TITLE
Installation issue w/ Pandas 0.16.2 on Ubuntu 15.10

### ISSUE THREAD

**Issue by bdeloeste** [crowdresearch/crowdsource-platform#629]
After installing dependencies, I attempted to migrate the database and ended up getting a ValueError with numpy/pandas.
![screenshot from 2016-01-12 02-32-54](https://cloud.githubusercontent.com/assets/5204249/12258552/25fe4b98-b8d5-11e5-95b5-b6df1125d561.png)

Was able to narrow it down to an installation issue with the pandas version in requirements.txt. 
![screenshot from 2016-01-12 02-32-54 copy](https://cloud.githubusercontent.com/assets/5204249/12258582/4abab4b2-b8d5-11e5-87f8-bc0ab049bea0.png)

I resolved the issue and was able to successfully run Daemo locally on my machine by uninstalling pandas and upgrading to pandas 0.17.1 with:
 
`easy_install pandas`

**Comment by psdh** [comment]
facing the same issue on ubuntu 15.04 too

**Comment by dmorina** [comment]
This was supported in 14.04LTS, feel free to raise a PR with the fix for 15.x
Thanks
