### ISSUE TITLE
Use placeholder text when creating new project/task

### ISSUE THREAD

**Issue by psdh** [crowdresearch/crowdsource-platform#631]
This would remove the need of deleting the default text when creating a new project

**Comment by willtchiu** [comment]
Sounds like a good idea! I'd also like to add that some of the placeholder text like in "Untitled Question" and "option #" could be substituted with placeholder text that gives an example of what kind of a question the task requester could ask and several appropriate placeholder text for options as well.

**Comment by dmorina** [comment]
it is more of a preference than a rule actually, deleting a line of text is not a problem :D 
it depends on the use case, in similar cases Google does the same i.e uses default text

**Comment by psdh** [comment]
@dmorina IMHO default text could be particularly useful if we could have different text for different users, depending upon their most requested task.
Placeholder text is just a nice thing to have, not a game breaker in any case.

Should we implement this, wait for more discussion or perhaps close this if it is unwanted now?

**Comment by mbernst** [comment]
I like the idea of default text, especially in the title. I'd start with
something simple, rather than making it unique per user.

**Comment by dmorina** [comment]
closing as irrelevant
