### ISSUE TITLE
Zooming in/out on login page permanently scales Daemo logo

### ISSUE THREAD

**Issue by willtchiu** [crowdresearch/crowdsource-platform#633]
* Using Safari 9.0, the Daemo label is not truly centered.
* Daemo logo scales with zoom in, but does not scale down with zoom out.
![screen shot 2016-01-12 at 11 38 56 pm](https://cloud.githubusercontent.com/assets/9894834/12288072/ed01cffc-b985-11e5-8b44-c3e09ce63629.png)

**Comment by dmorina** [comment]
fixed
