### ISSUE TITLE
Auto-focus 1st field in Sign in/Register Form/Forgot Password Form

### ISSUE THREAD

**Issue by musicakc** [crowdresearch/crowdsource-platform#634]
On signing in or registration, we can currently click on either of the options and the respective form is loaded for filling details. But the cursor doesn't automatically go to the first form field for you to start filling in. You have to first scroll down and then fill the details which should be automatic when you click on sign in/register. 
This would help in improving the user experience.

**Comment by dmorina** [comment]
agreed, these pages need a redesign and this issue should be addressed

**Comment by dmorina** [comment]
rename to 'Auto focus ..', maybe better

**Comment by shirishgoyal** [comment]
Completed in #650

**Comment by shirishgoyal** [comment]
Resolved in Resolve bugs #718
