### ISSUE TITLE
Actions can still be taken on already accepted submissions.

### ISSUE THREAD

**Issue by dineshdhakal** [crowdresearch/crowdsource-platform#635]
On the page for reviewing submissions for a given project, even after Accepting a task, you can again click the accept button. This is a little confusing.

Also the submissions can be returned or even rejected after already accepting it once.

<img width="1372" alt="screen shot 2016-01-17 at 11 13 56 pm" src="https://cloud.githubusercontent.com/assets/2520310/12378889/5dbc9d90-bd72-11e5-976b-70c8708ddbdc.png">

**Comment by dmorina** [comment]
this page has been redesigned this issue is addressed
