### ISSUE TITLE
authentication related forms

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/crowdsource-platform#637]
-go through the existing forms: login, register, change-password, forgot password; make sure the styling looks right, add ng-messages wherever they are missing

**Comment by Nalinc** [comment]
Currently, form validations are mostly being managed over server side(via crowdsourcing/validators/utils). Does this issue imply just enclosing (server-side) error-messages in `ng-message`(for better structuring) or having separate frontend validations? Also, should we follow the same styling as existing (server-side) error-messages or should we change the styles for both(frontend and serverend messages) altogether ?

**Comment by dmorina** [comment]
it depends on the type of validation (e.g email already, account not activated are all backend type) but some like required, min-length, max-length or pattern are all front end (there is a separate validation on backend), about styling they can differ that's ok
