### ISSUE TITLE
passwords should be encrypted much stronger.

### ISSUE THREAD

**Issue by kaushik94** [crowdresearch/crowdsource-platform#638]
I am able to see my password in the networks tab in chrome console after registration, which means anyone in my network can intercept the payload using wireshark and read the password. Client side encryption should be done.
<img width="689" alt="screen shot 2016-01-19 at 7 57 42 pm" src="https://cloud.githubusercontent.com/assets/6545467/12421268/5c5025d2-bee7-11e5-9299-a9bb1cfbe596.png">

**Comment by dmorina** [comment]
This is why sites run over https.

**Comment by kaushik94** [comment]
@dmorina I googled a completely different site which doesn't have http, my bad.
