### ISSUE TITLE
Requester Task Portfolio Dashboard Design

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#64]
### Task 
> 1. Enhance existing requester task portfolio dashboard design and theme   
> 2. Build requester's task portfolio page using HTML, Bootstrap, CSS. Incorporate angular tags for integration with services and controllers. At present, once a requester visits the task portfolio page, he get information about the tasks he has carried out. Tasks have ratings and reviews associated with it.  This page can be public i.e. available to other workers and requesters.  

___________________________________________________________________________________

### Technologies 
HTML, CSS, Bootstrap, Angular JS (beginner)     
___________________________________________________________________________________

### Related Issues
>1. Acceptance Test #68
>2. HTML, CSS, Bootstrap #64 
>3. Angular JS  #65 
>4. Rest API Data Models #66   	
>5. Automated Testing #67  

___________________________________________________________________________________
### References & Resources 

[Bootstrap Getting Started](http://getbootstrap.com/getting-started/)
[Bootstrap Tutorials](http://www.w3schools.com/bootstrap/)
[Microsoft EdX Bootstrap] (https://www.edx.org/school/microsoft)
[Codecademy HTML, CSS] (http://www.codecademy.com/tracks/web) 
[Codeschool  HTML, CSS] (https://www.codeschool.com/paths/html-css)
 
___________________________________________________________________________________

### Assigned 
GROUP 1
 
GROUP 2

___________________________________________________________________________________
### DRI
@neilthemathguy  

___________________________________________________________________________________

### Current profile page
Below is an example of required information. This will change and evolve as we progress. Therefore, be creative and add further enhancements. Also check related issues to satisfy front end requirements

![Design Reference]
(http://crowdresearch.stanford.edu/w/img_auth.php/b/bf/Task_portfolio.png)

**Comment by Macbull** [comment]
Shouldn't it be a Project or Module portfolio ? Only tasks are being referred throughout the current GUI . I am thinking of something like this. where rating is calculated by averaging all rating of task/modules. 
![requester dashboard](https://cloud.githubusercontent.com/assets/11361002/7903810/5f42bff0-0805-11e5-8d09-90351115992a.jpg)

**Comment by dmorina** [comment]
yes, modules or projects should be used, if it's a macro-project then a task=module
