### ISSUE TITLE
advanced options for authoring

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/crowdsource-platform#646]
-add advanced section in the gray area as a small link-text which expands the area and shows the advanced properties: let's start with `deadline` to be added to the Project model and the `timeout` field which exists already (this shows how long a worker can reserve a task for)

**Comment by Curious72** [comment]
@dmorina Should i make the deadline field nullable? also it should be a DateTimeField  right?

**Comment by dmorina** [comment]
Yes please for both statements :), thanks

**Comment by Curious72** [comment]
@dmorina so in which template do i have to make changes? and can you please tell me exactly what is to be done !

**Comment by dmorina** [comment]
Sure, will do a bit later today

**Comment by dmorina** [comment]
empty (collapsed)
<img width="1149" alt="screen shot 2016-01-26 at 8 53 57 pm" src="https://cloud.githubusercontent.com/assets/2858281/12604569/8d2ae748-c471-11e5-8e03-f8225f3dbe60.png">

filled (expanded)
<img width="1134" alt="screen shot 2016-01-26 at 9 10 00 pm" src="https://cloud.githubusercontent.com/assets/2858281/12604574/9d01cbc8-c471-11e5-8c62-8098cecbf417.png">

filled (collapsed)
<img width="1108" alt="screen shot 2016-01-26 at 9 11 43 pm" src="https://cloud.githubusercontent.com/assets/2858281/12604577/a98fd8ee-c471-11e5-9954-f8d9a98c8dd5.png">


Something along these lines (we might wanna check with the designers for the details cc @christopher.diemert)

**Comment by Curious72** [comment]
@dmorina Ohkay i got it !! can use ng-show for adding such functionality !!
