### ISSUE TITLE
extend data_source on authoring page

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/crowdsource-platform#647]
-allow requester to concatenate static text with column names from the spreadsheet file
something like `This is my question {column1} and this is the expected answer {column2}.`
spaces between `{}` can be ignored and it should highlight the {column}s as code.
data_source should be a list of objects `[{type: 'static', posititon:1, value: 'This is my question '}, {type: 'dynamic', value: 'column_1', ...}]`

this goes into the template_items of the authoring interface (create project) 
further discussions will happen on Slack

**Comment by Nalinc** [comment]
Can we have multiple occurrences of the **same** dynamic field ?
Like should we consider the case where `{column1}` is used twice/thrice in question-field ?

**Comment by dmorina** [comment]
No

**Comment by shirishgoyal** [comment]
I am wondering why it shouldn't allow multiple occurrences? 
We should infact replace all occurrences wherever applicable whether for same field or different one. We should not be limiting author on how these data sources can be used.

**Comment by dmorina** [comment]
That's the general case I agree, in practice I don't think it happens though, but sure go for it then

**Comment by Nalinc** [comment]
@dmorina, @shirishgoyal: In that case, what should be the structure of data_sources ?

Lets say we have the following question string. `"hello {column1} this is {column2} for {column1}"`.
- **option-1 having separate objects for multiple occurrences with their respective position.**
```
data_sources= [{
 type:'static',
 value:'hello',
 position:0
},{
 type:'dynamic',
 value:'column1'
 position:1
},{
  type:'static',
  value:'this is ,
  position:2
},{
  type:'dynamic'
  value:'column2',
  position: 3
},{
  type:'static'
  value:'for',
  position: 4
},{
  type:'dynamic'
  value:'column1',
  position: 5
}]
```

- option-2 using a single object for multiple occurrences and specify their positions in an array field
```
data_sources= [{
 type:'static',
 value:'hello',
 position:[0]
},{
 type:'dynamic',
 value:'column1'
 position:[1,5]
},{
  type:'static',
  value:'this is ,
  position:[2]
},{
  type:'dynamic'
  value:'column2',
  position: [3]
},{
  type:'static'
  value:'for',
  position: [4]
}]
```

**Comment by shirishgoyal** [comment]
I think lean way to handle this will be 
to store string value like "hello {column1} this is {column2} for {column1}" in val 
AND 
data_sources can contain a plain simple array [ 'column1', 'column2']

When task is created all the tags from data_sources are replaced in val in a single pass (to avoid recursive tagging)

We can use auto-complete while creating string above.
Let me know if you need more clarification.

**Comment by Nalinc** [comment]
@shirishgoyal : I postulated the same initially: to store _only_ dynamic tokens in `data_sources` since  static tokens are already being stored in 'value' attribute anyways. However, after discussing it with @dmorina in Wednesday meeting(27/1/2015), he suggested to keep both types in data_sources for better semantics. 

Also, following this scheme(to keep an array of objects with type, value and position attributes) fits well with the way we currently handle `options` field (in case of checkbox/radio-button/select-list questions).
![1](https://cloud.githubusercontent.com/assets/4050813/12696286/4ba82312-c78c-11e5-9672-10a9342d3bc1.png)

**Comment by shirishgoyal** [comment]
If you feel comfortable with that approach, that is fine too.

But options and data sources are two different things
Options need a way to be sorted. On other hand, data sources used in text have a fixed order already.
