### ISSUE TITLE
Add Auto-complete in addition to Link Column for Data Sources and Options

### ISSUE THREAD

**Issue by shirishgoyal** [crowdresearch/crowdsource-platform#656]
![image](https://cloud.githubusercontent.com/assets/315012/12783064/436f849e-caa5-11e5-9fe7-c446783ac31a.png)

a) Auto-complete should show all data columns available
b) Column added to data source / options will be available for use multiple times within same field

**Comment by Nalinc** [comment]
When do we expect to show the auto-complete drop-down ?
- On typing specific characters, say `{` (like we have in facebook/github when we try to tag a friend with `@` symbol) ?
- On typing initial few characters of the "dynamic column string" (like most of the auto-complete libraries offer) ?

**Comment by shirishgoyal** [comment]
Ideally , in both cases.

**Comment by Nalinc** [comment]
But wouldn't case (2) prevent the requester to use dynamic tokens as static ones?
Like I might want to use "column" within static text..and that could be a valid column name too. So if I start typing "col.." dynamic token would appear.

Also, do we have a design mockup for how it should look like? Should auto-complete dropdown look similar to "Link Column" dropdown?

**Comment by dmorina** [comment]
Nalin, we shouldn't prevent that, we dont have the design yet (we should wait on that)

**Comment by shirishgoyal** [comment]
No, that won't happen. Just typing token won't turn it into dynamic token. If we go by data_source structure, we will always show dropdown of tags to choose from which keeps filtering as user types the characters. Also all dynamic tokens will appear within { } in value so I don't see how static token will be misinterpreted as dynamic one.

No design mockup till now. It would appear like normal auto-complete works - show relevant options, allows filtering, click behaviour.
