### ISSUE TITLE
Requester Task Portfolio:  Data model and REST API

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#66]
___________________________________________________________________________________
### Task 
> 1. Enhance existing data model to support a requester's task dashboard 
> 2. Build REST API, view sets to support a requester's task dashboard  
> 3. Add dummy data to Validate the data model   
> 4.  At present, once a requester visits the task portfolio page, he get information about the tasks he has carried out. Tasks have ratings and reviews associated with it. This page can be public i.e. available to other workers and requesters.

___________________________________________________________________________________

### Technologies 
Python, Django Framework, REST API, PostgreSQL, Understanding of ORM 
___________________________________________________________________________________

### Related Issues
>1. Acceptance Test #68
>2. HTML, CSS, Bootstrap #64 
>3. Angular JS  #65 
>4. Rest API Data Models #66   	
>5. Automated Testing #67  

___________________________________________________________________________________

### Assigned 
GROUP 1
@Macbull @neilthemathguy

GROUP 2

___________________________________________________________________________________
### DRI
@dmorina  @elsabakiu  @neilthemathguy 
___________________________________________________________________________________

### Files
`crowdsourcing/models.py`
`crowdsourcing/serializers/requester.py`
`crowdsourcing/viewsets/requester.py`
`crowdsourcing/views.py`
`crowdsourcing/csp/urls.py`
`crowdsourcing/fixtures/`

___________________________________________________________________________________
### Reference
Below is an example of required information. This will change and evolve as we progress. Therefore, be creative and add further enhancements. Also check related issues to satisfy front end requirements

![Design Reference]
(http://crowdresearch.stanford.edu/w/img_auth.php/b/bf/Task_portfolio.png)

![Design Reference]
(http://crowdresearch.stanford.edu/w/img_auth.php/2/26/Data_Model_600_300ppi.jpg)

**Comment by Macbull** [comment]
Can anybody please explain the meaning of Task, Project, Module and Template with example ?

**Comment by neilthemathguy** [comment]
yes I will do it.

**Comment by dmorina** [comment]
A project is the biggest unit say it's name is "Building a crowd sourcing platform", a module can be a part of the project say there are 2 modules "front end design", "database design". If they are left like this then these two have 1 task each.
If it's a microtask project like on AMT then a module would be a group of same kind Tasks(hits). Templates are to be defined by the requester when creating the module for a microtask project

**Comment by Macbull** [comment]
thanks @dmorina

**Comment by Macbull** [comment]
Should ranking be associated with modules or with tasks ?  As, we may not be interested in rating a single task of labelling a particular image, however it would be useful to rate a complete module( comprising tasks to label images) of a project  ?

**Comment by dmorina** [comment]
ranking is based on a set of tasks, or complete module/project
