### ISSUE TITLE
Worker Based Task Review

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/crowdsource-platform#676]
To include worker based task review the following might be needed:

Projects should have a boolean property about if they are reviewable or not. 
If they are reviewable, we should store the task prompt and the work the worker contributes.

With some controllable periodicity, a recent task completed by a worker will be randomly selected and turned into a review task. **Review tasks are automatically issued by the Crowd Guild (which is a requester for the purposes of Daemo) and will operate as any other task in the Boomerang task feed.** The review tasks are placed in the task feed of a specific group of different workers (usually higher level workers).  

The review tasks shows the task prompt as well as what the original worker contributed. The reviewing worker will be able to read through these and then will have to enter 3 points of data to submit the review: 

1. a rating between 1 and 4 stars
2. a boolean about perceived acceptability of the evaluated work
3. an **optional** textual comment with no special formatting

This data is then connected to the original workers task history so they may view it at a later point and so that calculations for other purposes can be conducted on it. 

The review process is double blind, so neither the reviewer nor the reviewed know each other's identity.

**Comment by neilthemathguy** [comment]
@markwhiting: could you also add interface for Task Review?  We will need to define the system components based on three states: before the review, during the review, and post review. 

For instance consider following cases:  
1. *Before the review:*  Can a worker (reviewer) see the task status (returned/accepted) by a requester?Whether the review is voluntary or paid? If it is paid what the right amount? If it is voluntary whats the benefit, we will need to convey that via the interface (_The interface should clearly communicate the incentives_) 
2. During the review: The interface should communicate to the worker that his review is in progress (This information should reflect on either the worker's dashboard or on a separate review section). 
3. Post review: On the workers dashboard, we will need to communicate final results about his performance. We need to add right metaphors to communicate this information (e.g., returned over rejected)  On other hand, the worker's (reviewers) dashboard will need to highlight the review statistics (e.g., how many reviews were completed, percentage of acceptance/rejections, ratings provided, etc.). This data should be open to the guild community. 

Above are the examples to getting started with how the system will look like during each state of the review process. There is more to this -- over to slack

**Comment by qwertyone** [comment]
Post review is something that has been touched upon before. This is at
minimum a table with task name, status changes that differ for the
following user groups (requester, level 1 worker, > level 1 worker who is a
reviewer), and anonymous feedback.

Prior to this, there is an additional review of the review tasks that seeks
to eliminate poor reviews. This can be partial automation that creates
elimination through the introduction of character minimums greater than 10.
This eliminates "good", "none" type responses. This should be done after
review submission though.

**Comment by qwertyone** [comment]
http://2dfyag.axshare.com/task_review.html  a lot of work has been done by @alipta

**Comment by markwhiting** [comment]
1. Before the review: 
Can a worker (reviewer) see the task status (returned/accepted) by a requester? **No** 
Whether the review is voluntary or paid? **Paid** 
If it is paid what the right amount? **The hourly average pay for the reviewer's level** 

2. During the review: 
The interface should communicate to the worker that his review is in progress (This information should reflect on either the worker's dashboard or on a separate review section). **We down't show this. Reviews happen quickly, so progress is not so relevant, and randomly, so it is better if we give the worker as little prior knowledge of what is being reviewed as possible.**

3. Post review:
On the workers dashboard, we will need to communicate final results about his performance. **Yes, we have mockups for this. Basically:
1. star review will be shown on the completed task list for task that have been reviewed.
2. on click the review data, including rating and the optional comment will be shown
3. the last 10 reviews will be used for leveling with a moving average. I think it will be easier if I write a separate issue for leveling.
**

We need to add right metaphors to communicate this information (e.g., returned over rejected) On other hand, the worker's (reviewers) dashboard will need to highlight the review statistics (e.g., how many reviews were completed, percentage of acceptance/rejections, ratings provided, etc.). This data should be open to the guild community.

**Yes. We can talk more about this with designs etc.**

**Comment by markwhiting** [comment]
For context, the experimental context for task review is something like the following: 

1. Do workers choose to do review tasks when they are paid commensurate to the average hourly wage of the worker?

2. Do the simplified reviews they do correlate well with actual quality as measured by rubrics for several task types? (we have preliminary data on this from pilot 1)
2.1. Are there types of tasks that work better or worse for review?
2.2. How does worker level correlate with review accuracy?

**Comment by qwertyone** [comment]
Needed constraint in Feedback/Comment Box: Minimum character limit >10 if and after the box is ever made active by typing. AngularJS can do this.
![capture](https://cloud.githubusercontent.com/assets/6076358/14854271/5d5057fe-0c8f-11e6-9ea1-8f5c1a436e55.JPG)

**Comment by MHSSuliman** [comment]
@neilthemathguy and @markwhiting 
Can we include some social aspect to the reviwing system, like giving badgets to reviewers plus paying them for sure. 

The idea behind this is that our envision is building a sustainable system, open governance is a bout partcipation and engagement as well. The incentive structure should follow this vision.

**Comment by markwhiting** [comment]
@MHSSuliman Answered on Slack.

**Comment by Alipta** [comment]
Here is the explanation of how review of a task submission works, below is the task feed view of an L4 worker 
![taskfeed_view](https://cloud.githubusercontent.com/assets/8706501/14878814/8d456bc0-0d43-11e6-83c8-b92926fdc7d0.png) 

In the task feed the top one is the review task (highlighted in purple band), The reviewer clicks on details and lands to this page
![review_task_details](https://cloud.githubusercontent.com/assets/8706501/14878985/38ca4132-0d44-11e6-887a-f4212a4e9e0f.png)

The reviewer then rates the task by clicking on the stars
![review_task_me](https://cloud.githubusercontent.com/assets/8706501/14879034/7c5b2e20-0d44-11e6-8dcf-a2adebfee8cf.png)

The the reviewer click submit and then get a success message
![sucess_messge_postreview](https://cloud.githubusercontent.com/assets/8706501/14879104/dd7ecd4c-0d44-11e6-8a82-63b014479fa2.png)

**Comment by Alipta** [comment]
I assume in order to reuse template some changes were suggested by the #research-engineering The following mock up is recommended for Task Review

**Wireframe**
![task_review_new](https://cloud.githubusercontent.com/assets/8706501/14928772/8d6f4690-0e77-11e6-8944-90aff5310867.png)

**Visual Mock up**
![task_review_new_design](https://cloud.githubusercontent.com/assets/8706501/14928787/9cfc4f22-0e77-11e6-8591-2fae6efc23c9.png)

Please let the design team know if the above designs are good to go. The rating components are horizontally oriented to avoid vertical scroll bar and keep the maximum content above the fold.

**Comment by markwhiting** [comment]
I've made a few minor updates in this issue, particularly around boomerang and treatment of the guild as a requester.

**Comment by qwertyone** [comment]
The Slack Channels were given more than 24 hours to respond to this. Please let know how this can be improved if you run into any problems.
![guild co-creation space](https://cloud.githubusercontent.com/assets/6076358/14938859/959edc7a-0f32-11e6-8942-b622905ae18c.jpg)
![guild co-creation space 1]
(https://cloud.githubusercontent.com/assets/6076358/14938861/99ad4996-0f32-11e6-86de-78a4a5ddb973.jpg)
![guild co-creation space 2](https://cloud.githubusercontent.com/assets/6076358/14938863/9cce17f4-0f32-11e6-9e74-33fd566bc2b6.jpg)
![guild co-creation space 3](https://cloud.githubusercontent.com/assets/6076358/14938869/b1fc7148-0f32-11e6-8471-e444132c4a96.jpg)

**Comment by qwertyone** [comment]
![guild co-creation space 5](https://cloud.githubusercontent.com/assets/6076358/15031153/122aea3c-1257-11e6-9090-52ec938fcdc6.jpg)
![guild co-creation space 6](https://cloud.githubusercontent.com/assets/6076358/15031152/122875ea-1257-11e6-8c94-81239483cf15.jpg)
![guild co-creation space 7](https://cloud.githubusercontent.com/assets/6076358/15031154/122cb9b6-1257-11e6-8f7d-0cdb5a5ef679.jpg)
![guild co-creation space 8](https://cloud.githubusercontent.com/assets/6076358/15031155/1241372e-1257-11e6-88c7-e59050e69dce.jpg)
![guild co-creation space 9](https://cloud.githubusercontent.com/assets/6076358/15031156/124173f6-1257-11e6-8f47-13b53464d8a0.jpg)

**Comment by dmorina** [comment]
closing guilds issues
