### ISSUE TITLE
Crowd Guild Leveling

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/crowdsource-platform#677]
To facilitate leveling, we need: 

**1.** A level value for each worker.
**2.** A background process that computes the moving average of the last 10 reviews every time a worker gets a new review done on their work.
**3.** A table of leveling thresholds that might operate something like this: 
(assuming the ratings are on a 1-4 scale)

`if worker.movingAverage > 3.9: worker.level += 2`
`elif worker.movingAverage > 3: worker.level += 1`
`elif worker.movingAverage < 1.1: worker.level -= 1`
`else break`

So 4 cases are considered. 

1. Leveling up fast for excellent workers 
2. Leveling up good workers
3. Leveling down for exceptionally bad workers
4. Staying the same level

**4.** A background process that informs the worker and impacts the worker model when they are leveled up or down do to their moving average being in one of the 4 categories mentioned. After leveling the previous reviews are still viewable but none are applied to the next level, so a minimum of 10 more reviews are needed for the worker to experience another level shift.

**5.** Being in a different level impacts the tasks the worker sees. They now see tasks targeting their new level first, (presumably in boomerang order), then tasks from lower levels.

**6.** Average hourly wage is computed for each level based on:

the sum of all the pay received by all the workers in the level for tasks they have completed since joining the level divided by the sum of all the time expected for all those tasks based on prototype task duration predictions.

**Comment by markwhiting** [comment]
Closed by accident.

**Comment by markwhiting** [comment]
The experimental context for leveling is: 

1. Does this leveling method lead to higher correlation with worker's average task quality vs acceptance based reputation methods (e.g. taking the acceptance rating of the worker from Mturk)

2. Is the 10 review moving average effective for: 
2.1 Moving great workers up fast enough
2.2 Getting good workers to a level they can stay at
2.3 Avoiding bad workers getting leveled (including avoiding malicious workers)
2.4 Keeping workers motivated to maintain their focus on quality.

3. What are the sociological and psychological impacts of leveling? This will be evaluated mostly through questionnaires and analyzing things like forum contributions.

**Comment by qwertyone** [comment]
Possible Leveling Rule System: 
If the average value of the last N reviews is in a category of A, the worker's level will be changed accordingly.  

Level 1 Goal: demonstrate mastery over Daemo
- If the Level 1 worker completes last N tasks with X acceptance rate once, the worker increments from Level 1 to Level 2. This is permanent. 
Level 2: Task Proficiency
- If the Level 2 worker completes last N tasks with X Leveling Threshold AND completes last M reviews, the worker increments from Level 2 to Level 3. 
Level 3: Provide Reviews for Peers
- If the Level 3 worker completes last N tasks with X Leveling Threshold NAND does not complete last M reviews, the worker decrements from Level 3 to Level 2. 
Level 4: Demonstrate the Ability to Distinguish Good/Bad Work in Reviews
- If the Variance of the last M reviews is in a Category of A is > 0 AND submits N tasks with X Leveling Threshold, the worker increments from level 3 to level 4. 
- If the Variance of the last M reviews is in a Category of A is = 0 NAND submits N tasks with X Leveling Threshold, the worker decrements from level 4 to level 3.

**Comment by markwhiting** [comment]
@qwertyone Based on our last discussion, lets stick to the simplest level rule for now and expand from there if we see evidence that necessitates specific changes.

I think the other level rules you're mentioning are interesting and we can develop them further as we move forward.

**Comment by mbernst** [comment]
Depends on #676

**Comment by markwhiting** [comment]
@Nalinc - I think you said you would be able to help do this part. Please let us know if there are any areas where more clarity is needed.

**Comment by markwhiting** [comment]
Heres a minor updates regarding the positioning of level information in the interface (this was a question brought up when we had the engineering call on Friday). 

The level information can be positioned in the header near the username as shown in this image.
![daemo_level](https://cloud.githubusercontent.com/assets/673171/14940084/46e7933c-0f33-11e6-9fce-46d122411bad.png)

**Comment by Nalinc** [comment]
@markwhiting: Thanks for the mockup. Yes I'll handle this issue :)
 but this would need us to have the updated user model which is primarily what #676 is about. Also I presume we are going with 3 levels for the current study, right?
Because this should be coherent with the levels-badges we have in forum.

**Comment by markwhiting** [comment]
You are right, we need the updated user model. 

We don't have a hard cap on levels. I think it needs to be compatible with being higher than 3. So in the forum, levels can be represented by a number, that is not connected to the forum activity levels.

**Comment by dmorina** [comment]
closing guilds issues
