### ISSUE TITLE
Crowd Guild Requester Features

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/crowdsource-platform#678]
There are several features for requesters, however, due to the specific experimental setup its likely some of them won't need a lot of focus at this point. 

**Task Authoring for Levels**
After requesters have completed the prototype task workflow they will have the opportunity to select what level workers for their task should be. This is similar to how MTurk lets us select Masters. The requesters will be shown some recommended pricing information, based on the prototype task rate, and the average hourly wage of workers of each level.

**Task Rejection**
If workers think requesters are underpaying in a specific task, for their level, they can reject a task from the task details page, or from within the task. Rejecting does not allow them to receive any money for that task, and removes it from their feed. The requester will get a notice that this has happened. If a large number of workers reject tasks in this way from the same project, then the project will be removed. 

Right now we don't know what that _large number_ will be.

**Experimental Context**
We are not intending to run this live with requesters, because we don't think we can recruit enough for that. Instead, we would like to collect data from workers about quality and price reaction (e.g. rejecting, performing better or worse etc.) and then set up a game for a few requesters to play in which they can choose how much to pay workers for a specific task and which level workers to target. They will get feedback based on the recorded real worker data based model and we will see how they change their behavior over several iterations of the game.

As a result, the task authoring for levels and task rejection sides are not needed in full, but just a few parts in the way we deal with the data are needed at this point.

**Comment by qwertyone** [comment]
High level goal|	Sub Goal|	Sub Goal	|Sub Goal	|Sub Goal|	Sub Goal|	User Goal|Scenario|	Step|	Sub-Step	|User Physical Action (operations)	|Notes
1	|1	|2	|0	|0	|0	|To gather more information about a task||||					
||||||							A|	1|		|User identifies  [TASK LIST ITEM] to explore|	
||||||							A|	2|		|User moves cursor above  [TASK LIST ITEM]	|
							A	3		User clicks [TASK LIST ITEM] to expand details	
1	1	2	1	0	0	To reject a task after elaboration					
							A	1		User clicks [TASK LIST ITEM] to decrease details	
							B	1		User moves mouse cursor over [TASK LIST ITEM]	
							B	2		User clicks different [TASK LIST ITEM]	
							C	1		User moves cursor to [REJECT BUTTON]	
							C	2		User clicks cursor over [REJECT BUTTON]	
1	1	2	1	1	0	To explain task rejection					
							A	1		User views [REJECTION LIST FORM]	options include [LOW PAY only for study]
							A	2		User moves cursor over [REJECTION LIST FORM]	
							A	3		User clicks [UI ELEMENT] s from [REJECTION LIST FORM]	
							B	1		User read [PROMPT]	prompt reads "Is there another reason why you reject this task?"
							B	2		User moves cursor over  [REJECTION LONG FORM TEXT FIELD]	
							B	3		User clicks cursor over  [REJECTION LONG FORM TEXT FIELD]	
							B	4		User types rejection reason in [REJECTION LONG FORM TEXT FIELD]	
							C	1		User read [PROMPT]	prompt reads "What would repair this task?"
							C	2		User moves cursor over  [REPAIR LONG FORM TEXT FIELD]	
							C	3		User clicks cursor over  [REPAIR LONG FORM TEXT FIELD]	
							C	4		User types rejection reason in [REPAIR LONG FORM TEXT FIELD]	prompt reads "Error. Please leave empty of if filled must be >10 characters."
1	1	2	1	1	1	To submit task rejection					
							A	1		User moves cursor to [SUBMIT BUTTON]	
							A	2		User clicks cursor over [SUBMIT BUTTON]	
1	1	2	1	1	2	To cancel task rejection

**Comment by qwertyone** [comment]
**Task Review Mockup: from @alipta and explained in the HTA**
![capture](https://cloud.githubusercontent.com/assets/6076358/14853743/10feb3c0-0c8d-11e6-814d-cc2928b669b0.JPG)

**Comment by qwertyone** [comment]
**Possible Changes to the Task Stream for Workers GREATER THAN LEVEL 1**
_We are proposing no major changes to the task stream. The only differences will be noticed by workers higher than level one after they have demonstrated competency through task acceptance (i.e. a measure that they can use the Daemo system successfully). The changes would be a notice of level information or a task identified as "REVIEW" in text or possibly the placement of review tasks at the top. 3 options for this. Overall we are positioning review tasks to be handled in a way similar to requester tasks with all of the same functionality._
![capture](https://cloud.githubusercontent.com/assets/6076358/14853819/54dd4ac0-0c8d-11e6-9e16-3590feba9266.JPG)

**Comment by markwhiting** [comment]
@qwertyone I think the images you've posted here are part of some of the other features, not quite the requester facing part. 

Because we are not running with requesters we probably don't need as much development in this area, we just need to be able to set up the toy problem mentioned above.

**Comment by Alipta** [comment]
I think the moc up for Task Stream for Workers GREATER THAN LEVEL 1 is already in place
![taskfeed_view](https://cloud.githubusercontent.com/assets/8706501/14878144/3d178f2e-0d3f-11e6-8d3a-1ceceeae5ef1.png) There is a slight change in the design pattern as the current daemo app is using accordion menu to display task details, but in our case we are asking user to click on the details button positioned at the right end of task feed. Once the user click on details he will get to see the description of the task 
![task_detailsl4](https://cloud.githubusercontent.com/assets/8706501/14878208/b4c07e46-0d3f-11e6-94b3-aed5c7ee0386.png)

**Comment by dmorina** [comment]
closing guilds issues
