### ISSUE TITLE
Projects and Tasks with Access Restriction in Daemo

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/crowdsource-platform#682]
Many of the Crowd Guild features rely on being able to send specific tasks to specific workers, not just change the order of their task feed. 

To facilitate this several types of restrictions could be useful if added to Daemo:

**1. Restriction to workers or worker groups** - a project could target a specific group of workers such as workers by ID or by a group identifier (which might basically just be an ID for a guild level or similar). Optionally, workers not targeted might not see these tasks at all.

**2. Restriction to repeated work** -  a project could specify that a given worker can do only one of a set of tasks, or some specific number, or some specific percentage of a set of tasks. Once they have fulfilled this requirement, they would optionally not appear in the effected workers feeds anymore.

The options around visibility are another aspect of this, and I'm not sure if that is enabled at this time, but if not it would be very helpful to make these types of restrictions effective.

**Comment by markwhiting** [comment]
Might be quite similar to #660.

**Comment by dmorina** [comment]
closing as irrelevant
