### ISSUE TITLE
Crowd Guild Task Feed Features

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/crowdsource-platform#683]
The Crowd Guild system operates on the notion that workers can work on tasks that are targeted at their level and any level below them, and not work on tasks from levels above them.

Levels and reviews are indicated with tags. Color bars on the left of tasks also align with levels as @Alipta has shown below. Boomerang features are also visible for all tasks including the review task, which is hosted by the Crowd Guild.

**Comment by qwertyone** [comment]
Additionally,  it would be nice to enable workers to rate the guild as a
requester through the boomerang. This would provide a mechanism to connect
event logs with the rating. Guilds do not rate workers.

**Comment by qwertyone** [comment]
![pasted image at 2016_04_27 07_01 pm](https://cloud.githubusercontent.com/assets/6076358/14938886/7da49b36-0f33-11e6-86ca-07f6c389df58.png)

**Comment by Alipta** [comment]
The task feed view got revised, 
![taskfeed_list_view_0 2](https://cloud.githubusercontent.com/assets/8706501/14938896/2544ef72-0f51-11e6-91af-21632aa92bbc.png)

This is the expanded view of the Review task on click of "Details" 
![task_review_new_design](https://cloud.githubusercontent.com/assets/8706501/14938953/ba6904f2-0f52-11e6-9589-18218a29ccc1.png)

**Comment by qwertyone** [comment]
It would be great to use that every "DISCUSS" link to auto-generate a new thread and {{Tag.TaskTitle}} in the forum upon first click occurrence and then leads people to the same thread every click thereafter. This will demonstrate the effectiveness of the system to capture questions at the moment they arrive.

**Comment by dmorina** [comment]
closing guilds issues
