### ISSUE TITLE
authoring updates

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/crowdsource-platform#690]
-add slider item
-add `pattern` to input fields
-add static text component √
-steppers (?)

**Comment by markwhiting** [comment]
- optional input (right now errors seem to happen when we treat one as this and people don't fill it out)

**Comment by qwertyone** [comment]
https://crowdresearch.slack.com/archives/research-engineering/p1463146828000185

Please examine the non-submission error that seems to be caused by two
consecutive number text fields.

**Comment by markwhiting** [comment]
- preview task would be super helpful. 
- embedding content from a remote site is not working (other off site things also have been having trouble, e.g. Image Container)
- being able to enter HTML or something like that so we could have rich links instead of just pasting urls would be good

**Comment by dmorina** [comment]
iframe should work, just make sure you are using `https`

**Comment by markwhiting** [comment]
- cvs with unescaped characters brings the world crashing down!

**Comment by markwhiting** [comment]
- when task timer is not set, it should not appear in the tasks, or should appear as "Unlimited" or something equally optimistic.

**Comment by markwhiting** [comment]
Not sure if this is a bug, but timers on skipped tasks remain active. 

If we are going to do this this way, perhaps we could give a tooltip that explains this. Some workers find this pretty strange.

**Comment by markwhiting** [comment]
- We're having issues where parts of a task are sometimes randomly reordered after a task is published.

**Comment by qwertyone** [comment]
To add -- restrict number test fields to numbers only. Workers will
introduce text in the short text form which was intended for numbers only,
which makes it difficult to perform automated analysis later.
