### ISSUE TITLE
My Tasks Redesign - Running Total of Accepted/Completed Tasks + Pay

### ISSUE THREAD

**Issue by FreddieV4** [crowdresearch/crowdsource-platform#692]
Hello there. So after sifting through some comments & the platform, it looks like there should be a running total of tasks that are accepted by workers as well as ones that are completed, with a running sum of the total pay they should receive. 

I think we may have already some sort of implementation of this, but it's buggy?

**Comment by mbernst** [comment]
ccing @dmorina

**Comment by markwhiting** [comment]
Theres a little bit of a lack of transparency here that workers are not thrilled by. I'm not sure we can really provide a solution to that, but it might be nice to offer some kind of way they can get more information about pay on the tasks they are done with.

**Comment by markwhiting** [comment]
A way we might improve this is if the 'My tasks' list shows the price of accepted work in a task, or something similar. 

Many workers are complaining that they can't see what has been accepted easily and can't see how much they should be being paid for it.

**Comment by mbernst** [comment]
@dmorina how hard would that be to add?

**Comment by dmorina** [comment]
per task should be relatively easy, i can add that

**Comment by dmorina** [comment]
closing as irrelevant to release 1.0
