### ISSUE TITLE
Not loading properly in chrome

### ISSUE THREAD

**Issue by dinukadesilva** [crowdresearch/crowdsource-platform#695]
HI, 

I just tried accessing https://daemo.stanford.edu/login which is an initial work of Daemo as I found in http://crowdresearch.stanford.edu/w/index.php?title=Main_Page. So, I found that it's not working in Chrome but, working in Firefox. 

![image](https://cloud.githubusercontent.com/assets/10680296/15269159/675faa8c-1a14-11e6-902d-1779a0ff7663.png)

Chrome [Version 50.0.2661.102 m]
Firefox [Version 49.0.1]

Still I'm new to the community. I would like to contribute. So, I just registered from the google form provided provided in the page. I'l also try to look into the issue while going through the project.

Thanks

**Comment by shirishgoyal** [comment]
Closed in Authentication fix #390 
Changes yet to be pushed to production site, which has a stale version at present.
