### ISSUE TITLE
Review Updates

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/crowdsource-platform#697]
A few things that would really help reviews work better

1. task authors should have a checkbox about if a task is reasonable to review or not (with its default state as on)
2. task authors should, for now, be asked to estimate how long they think a review will take to complete. This should then be used to set the price of the review (assuming our usual hourly rate for now).
3. it might be nice to be able to auto accept reviews

**Comment by dmorina** [comment]
closing guilds issues
