### ISSUE TITLE
Requester Authoring Wishes

### ISSUE THREAD

**Issue by qwertyone** [crowdresearch/crowdsource-platform#699]
Scenario: A requester is in need of posting a survey, with the same scale measures, that is greater than 9 questions. Somewhere in the process, as he begins proofing his instrument and repeats a cycle of scrolling up and down and eventually the changes and proofing he performs become for naught.

Error: Overlooking an overall instrument error. When a requester publishes a HIT, Daemo pops up the prototyping box. This leads me to immediately publishing. There are times as a requester when I know what I would like to publish. However, there is not real preview of the task as presented to the requester to confirm this.

Current Work Around: visiting the task stream to confirm the end product in the drop down menu.

Solution: a preview window or some other means to see what the worker will see. 

Human Error: On surveys Daemo seems designed to handle small microtasks of 1 to 5 questions. Depending on the workflow I choose, I will run into a problem proofing my survey scales in bulk.

Current Work Around: scrolling through the task to verify that the buttons are right and there exist no typos.

Interface Solution: Matrix Scale System
[more details](http://help.surveymonkey.com/articles/en_US/kb/Matrix-Question)

**Comment by qwertyone** [comment]
Scenario: As a requester, I decided that I would author a task directly from a word file. I have two windows open - the survey question and the task to be authored. I fill in the HIT title. Then I copy the  my first question and paste it into Daemo's default radio button element. I realize at that moment I need a text box response field. I click the text box icon and the text box element appears. I click the text input field of the text field element and paste my first question into the box. I can't. [BUG] The element field options appear open below as I do this and voids my effort. I repeat it again successfully.

In a situation when I had to rearrange the questions of a survey within the task authoring interface, this same bug appears as I hit the delete button on the text field of an already created yet inactive, unexpanded element. The result is that the delete key sends me back through the browser history according to the number of times I hit it.

**Comment by qwertyone** [comment]
WISH: TASK CSV Output to have the question name or an identifier of the question in the Columns.

Currently the CSV is reversed order from the sequence of the authored task. It is a little jarring. Possibly have the output match the input.

**Comment by qwertyone** [comment]
WISH: TASK CSV Output would produce columns with TRUE/FALSE responses their respective row rather than a python array.

Currently the download CSV button produces in a single cell response to a large checkbox input field from a task.
https://crowdresearch.slack.com/files/anotherhuman/F19N768VA/example.txt

As the rows populate with other responses such as this, the variability between them becomes difficult to interpret as to what needs to be done to clean out the output.

**Comment by qwertyone** [comment]
![image](https://cloud.githubusercontent.com/assets/6076358/15406335/66ac4730-1e06-11e6-9467-7330f56b3fd0.png)

The confirmation of task acceptance for the requester is neither providing instant feedback nor delayed updating.

**Comment by dmorina** [comment]
we need to break this down to small concrete issues/features closing for now
