### ISSUE TITLE
Feature Request: Member Activity Status Icon

### ISSUE THREAD

**Issue by qwertyone** [crowdresearch/crowdsource-platform#700]
"I was just thinking that it would be very helpful/useful to have some type of notification that signifies if a Forum Member is Currently Active/On or if they are Away etc.. If we knew that specific Members were Online, we would feel more connected and have a sense that we have someone to turn to in real time. Status Notification could be, perhaps, a little green dot under our user Profile Avatar when we are Active; red when we aren't (not that I know how easy or hard this is to accomplish)."

Requested feature from worker - http://daemo-forum.herokuapp.com/t/daemo-member-status-wish-list/113?u=anotherhuman

**Comment by dmorina** [comment]
closing guilds issues
