### ISSUE TITLE
Feature Request: Accepted/Unaccepted Task Status Differentiation

### ISSUE THREAD

**Issue by qwertyone** [crowdresearch/crowdsource-platform#702]
ducky Guild Member3h
I might be a minority, but I've found myself forgetting not accepting a task and then beginning work before realizing it. It's just a minor inconvenience for the most part, but having the color of an unaccepted task be slightly different than the accepted task would help this immensely!

**Comment by dmorina** [comment]
noted, we will disable items on preview

**Comment by dmorina** [comment]
irrelevant as we nuked the worker side
