### ISSUE TITLE
Task Creation Workflow: Data model and REST API  

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#71]
___________________________________________________________________________________
### Task 
> 1. Enhance existing data model to support templates for the Micro Tasks creation workflow
> 2. Current micro task categories: Image Tagging, Writing, Survey, and Data Collection  
> 3. The current model can be extended to store template in `JSON` format using `JSONField` mapped to postgresql `JSON` data type
> 4. Build REST API and views to support the workflow 
> 5. Add dummy data to Validate the data model  

### Task Creation Workflow API will support:  
**Progress Headers and Forms Sequence**
> 1. Category Selection
> 2. Create task  
>3. Milestones or Input transducers (Input and output transducers: Tasks get vetted or improved by people on the platform immediately after getting submitted, and before workers are exposed to them, see the [research foundation] (http://crowdresearch.stanford.edu/w/index.php?title=GettingStarted)
>4. Task scheduler 
>5. Payment Mechanism  
>6. Task Review & Submit 

Be creative and enhance the suggested workflow to make it better 
___________________________________________________________________________________
**Form 1: Select the category** 
Progress HEADER: Highlight the Six Step Registration process, *Category Selection* Active others inactive 
> 1. Select the task from different categories
>2. User hits Next 
___________________________________________________________________________________

**Form 2: Dynamic Loading of the templates** 
Progress HEADER:  *Create Task* Active others inactive 
> 1. Present various templates thumbnails 
> 2. Let user select one of the templates  
>4. User hits Next 
___________________________________________________________________________________

**Form 3: Add Milestones, Rubrics, or Input Transducers** 
Progress HEADER *Add Milestone* Active others inactive 
> 1. Let user create the milestones to break down the project in multiple phases. Example: Milestone 0: Task Testing / Input Transducer 

___________________________________________________________________________________

**Form 4:  Task Scheduler**  
Progress HEADER *Task Scheduler* Active others inactive 
>1. Add calendar and time to indicate the task activation event
>2. Add the duration - how long the task will run? 
>3. (Ignore: Task Update: How can requester add more time to the existing task?)

___________________________________________________________________________________

**Form 5:  Payment Mechanism**
Progress HEADER  *Payment* Active others inactive 
>1. Current balance indicator
>2. Highlight minimum payment requirements 
>3. Interface to add more funds to support  

___________________________________________________________________________________

**Form 6:  Task Review & Submit**
Progress HEADER *Task Review* Active others inactive 
>1. Provide Single page Task Summary highlighting 1-5.  
>2. Option to Edit any of the sections 
>3. Release task button 

For reference [please see](http://crowdresearch.stanford.edu/w/img_auth.php/c/cc/NeilgaikwadEWF.png)

___________________________________________________________________________________

### Technologies 
Python, Django Framework, REST API, PostgreSQL, Understanding of ORM 

___________________________________________________________________________________
### Related Issues
>1. Acceptance Test #88
>2. HTML, CSS, Bootstrap #84 
>3. Angular JS  #76  
>4. Rest API Data Models #71     	
>5. Automated Testing #87 

___________________________________________________________________________________

### Assigned 
GROUP 1
 
GROUP 2

___________________________________________________________________________________
### DRI
@dmorina  @elsabakiu  @neilthemathguy 

___________________________________________________________________________________

### Files
`crowdsourcing/models.py`
`crowdsourcing/serializers/template.py`
`crowdsourcing/viewsets/` //Create one for template classes 
`crowdsourcing/views.py`
`crowdsourcing/csp/urls.py`
`crowdsourcing/fixtures/`

`serializer classes TemplateSerializer TemplateItemSerializer  TemplateItemPropertiesSerializer`
`models TemplateTemplateItem  TemplateItemProperties Task`
_____________________________________________________________________________
### Reference
Follow/enhance the classes in Blue 

![Design Reference]
(http://crowdresearch.stanford.edu/w/img_auth.php/2/26/Data_Model_600_300ppi.jpg)

**Comment by webmaven** [comment]
@dmorina Was this task closed because the work happened elsewhere?

**Comment by dmorina** [comment]
yes, this was a general issue long ago, which covers the task authoring api and interfaces

**Comment by webmaven** [comment]
Links to the relevant PRs or branches?

**Comment by mbernst** [comment]
Trollface.png ?

On Sunday, November 22, 2015, Michael R. Bernstein <notifications@github.com>
wrote:

> Links to the relevant PRs or branches?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crowdresearch/crowdsource-platform/issues/71#issuecomment-158818001>
> .
>


-- 
sent from my NLS

**Comment by webmaven** [comment]
I think you meant :trollface:, but no, I wasn't actually.
