### ISSUE TITLE
Demographics

### ISSUE THREAD

**Issue by sharonzhou** [crowdresearch/crowdsource-platform#713]
Collect demographics for each worker.

Displayed on worker's profile: age, gender, race, occupation/profession, location, computer usage, languages - native, languages - fluent, income level, education level

Also captured via Google analytics: OS, browser, location

Not displayed (?):
Marital status, religion, political affiliation, news interests

Later:
Currency

**Comment by shirishgoyal** [comment]
Closed in User profile demographics and caching ref #714 #716
