### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by bigcrowd** [crowdresearch/crowdsource-platform#717]
Hello.

When i registred and confirm with link i can't authorization. If I enter the wrong password or username - shows me a message. If I enter a valid username and password - nothing happens.

**Comment by bigcrowd** [comment]
In terminal , after i try login - "POST /api/auth/login/ HTTP/1.1" 500 135561

**Comment by dmorina** [comment]
not able to replicate

**Comment by mcavdar** [comment]
same issue

**Comment by hiteshvaidya** [comment]
same issue. When I enter correct id, password, nothing happens i.e. control is not passed to next page.
