### ISSUE TITLE
ImportError: No module named oauth2_backends

### ISSUE THREAD

**Issue by Paul-Hoo** [crowdresearch/crowdsource-platform#735]
Hi everyone, when I try to deploy this on a CentOS7, no matter I use Vagrant, or use step-by-step setup, when come to `python manage.py runserver` , it says 

> ImportError: No module named oauth2_backends

I tried `sudo pip install xxxxx`, but no luck.
Any solution? THX.

BTW.: there is no more ubuntu/vivid32 from atlas.hashicorp.com, right? I chose precise32 instead, is this all right?

**Comment by dmorina** [comment]
not able to replicate, possibly missing the python package
