### ISSUE TITLE
"Key" is overloaded and has two meanings

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#738]
There is both "Project Key" and "key" in the UI. We need to give them different names:
<img width="451" alt="screen shot 2016-08-11 at 5 31 16 pm" src="https://cloud.githubusercontent.com/assets/249285/17609384/73ed47a8-5fe9-11e6-961a-6ca8686aaa10.png">

How about the bottom one becomes "field name"? "Private name"? "ID"? "Field key", so at least it's differentiated from "Project Key"? Other ideas? @shirishgoyal @nevenwt?

**Comment by dmorina** [comment]
field name sounds reasonable

**Comment by shirishgoyal** [comment]
Changed to "Field name"
