### ISSUE TITLE
Should we allow spaces in the field key/id/name?

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#739]
<img width="443" alt="screen shot 2016-08-11 at 5 34 56 pm" src="https://cloud.githubusercontent.com/assets/249285/17609420/f0b38900-5fe9-11e6-984a-efae93f020d1.png">

I could see arguments either way. CSV would be fine with spaces, and so would a lookup in a Python dict. So I think it's OK?

**Comment by dmorina** [comment]
I think it's fine, not pretty with spaces but ok

**Comment by mbernst** [comment]
ok!

**Comment by dmorina** [comment]
closing, no issues with PEP8
