### ISSUE TITLE
Can we render the payment in $D.CC format?

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#741]
Currently:
<img width="85" alt="screen shot 2016-08-11 at 5 37 11 pm" src="https://cloud.githubusercontent.com/assets/249285/17609460/42eb8038-5fea-11e6-9b96-c018c6699596.png">

I think it will be clearer if we autoformat it to look like "1.00" instead of "1". Otherwise it's not clear if I'm paying one cent or one dollar. Also we can add a static "$" to the left of the field.

**Comment by dmorina** [comment]
i think the unit $/task makes it clear that it's dollar not cents but i could see that being confusing.
It's not that easy as you cant use `currency` filter in ngModel. However, a custom directive should do it (relatively small one)

**Comment by dmorina** [comment]
i take that back :D, if we want that formatting we would have to do `type="text"` instead of number and that's not nice, I would suggest keep it as is (maybe add same information elsewhere as summary as a `span` which can be formatted easily  as currency

**Comment by shirishgoyal** [comment]
![image](https://cloud.githubusercontent.com/assets/315012/17951955/ef3cba0c-6a1a-11e6-8eae-2c997a7603bd.png)

Added $ as prefix to price field
Adding decimal fields like 0.00 is not possible in browser by default (without requiring timer and type as text) as decimal values like .00 do not trigger any event.
