### ISSUE TITLE
Visual design on my projects table

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#743]
Right now it looks like:
<img width="822" alt="screen shot 2016-08-11 at 5 43 00 pm" src="https://cloud.githubusercontent.com/assets/249285/17609549/19c9a1fc-5feb-11e6-87fb-75706279f097.png">

1) This looks funky between there's very little margin between the title column and the next one. Can you increase margins?

2) Also, top-align the text so that "Draft" is vertically aligned with the top row of the title text.

3) There's a ton of space dedicated to the Status and Last modified columns. They can be much smaller, so we can make Name bigger.

4) Edit is hidden under a context menu that has very little information scent:
<img width="370" alt="screen shot 2016-08-11 at 5 45 29 pm" src="https://cloud.githubusercontent.com/assets/249285/17609583/722d69b4-5feb-11e6-9a70-b47cede61483.png">
Instead, I suggest linking the project name to the edit page for that project. Delete can either stay in the context menu, or just use a trashcan icon in the table itself and ditch the context menu.

**Comment by dmorina** [comment]
this view needs some more major changes (needs redesign)

**Comment by dmorina** [comment]
<img width="831" alt="screen shot 2016-08-12 at 10 05 10 am" src="https://cloud.githubusercontent.com/assets/2858281/17630501/6d01fb1a-6074-11e6-865c-165394be87a9.png">
