### ISSUE TITLE
Inconsistent naming Project vs. Task

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#744]
I "create a project" and look at "my projects", but when I'm editing, it's called "Task Authoring":
<img width="843" alt="screen shot 2016-08-11 at 5 47 35 pm" src="https://cloud.githubusercontent.com/assets/249285/17609645/d46b9952-5feb-11e6-8c29-90ffd1407257.png">

I suggest being consistent: either "Project Editing"/"Project Authoring" or call everything "Tasks".

**Comment by mbernst** [comment]
Also "Project Key". (I assume the right answer is to change Task to Project in the title here.

**Comment by mbernst** [comment]
Also apparently I have a Bitmoji plugin on GitHub???
![bitmoji](https://render.bitstrips.com/v2/cpanel/8149260-70639404_3-s1-v1.png?transparent=1&width=246)

**Comment by dmorina** [comment]
i think the project concept makes sense, will rename to Project Authoring
