### ISSUE TITLE
Slight misalignment of headings

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#748]
Not sure if this is easy to fix, but the headings are annoying off the left rule of the descriptions. For example, the Q in qualifications is further left than the A in Attribute:
<img width="126" alt="screen shot 2016-08-11 at 5 57 31 pm" src="https://cloud.githubusercontent.com/assets/249285/17609812/317ac40a-5fed-11e6-85bb-99bd0e7f4b3b.png">

**Comment by dmorina** [comment]
mmk
