### ISSUE TITLE
Rendering error in qualification textbox

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#749]
It's exploooding
<img width="183" alt="screen shot 2016-08-11 at 5 58 47 pm" src="https://cloud.githubusercontent.com/assets/249285/17609824/4f544488-5fed-11e6-8b22-b060945deb3b.png">

**Comment by dmorina** [comment]
<img width="116" alt="screen shot 2016-08-11 at 9 48 38 pm" src="https://cloud.githubusercontent.com/assets/2858281/17613037/c23577ae-600d-11e6-90c5-75847aab04a6.png">

**Comment by mbernst** [comment]
Toggle the Attribute textbox back and forth to replicate.
