### ISSUE TITLE
Qualification "Add" button is always disabled?

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#750]
I can't get it to become accessible. Am I missing something?
<img width="420" alt="screen shot 2016-08-11 at 6 00 18 pm" src="https://cloud.githubusercontent.com/assets/249285/17609849/79eefbb6-5fed-11e6-86f9-616ccd7e0893.png">

**Comment by dmorina** [comment]
<img width="597" alt="screen shot 2016-08-11 at 9 46 37 pm" src="https://cloud.githubusercontent.com/assets/2858281/17612995/1aea349e-600d-11e6-96b0-67278f694db6.png">

**Comment by dmorina** [comment]
weird!
console logs-> any errors? steps to reproduce?
