### ISSUE TITLE
Are the qualifications on Daemo or AMT?

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#751]
Approval Rate and Number of completed tasks...are these based on data on AMT, or on our platform? I worry about people being confused which one it is. If it's Daemo, we should say "Daemo approval rate" and "Number of tasks completed on Daemo"

**Comment by dmorina** [comment]
our platform, alright

**Comment by mbernst** [comment]
I wonder: should we remove them for now? I think it's going to confuse people who think of us as a layer on top of AMT. Is there a reasonable case that people would want to use these?

**Comment by dmorina** [comment]
this cannot translate 1to1 to AMT unfortunately, we should discuss this

**Comment by mbernst** [comment]
OK, let's discuss

**Comment by dmorina** [comment]
my guess is that people might wanna use the ones of AMT (?) not sure
