### ISSUE TITLE
"Add new" does nothing

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#753]
I click and I get nooooothing
<img width="255" alt="screen shot 2016-08-11 at 6 03 03 pm" src="https://cloud.githubusercontent.com/assets/249285/17609892/de1caa0c-5fed-11e6-8d6e-7c8ef48c199d.png">

Is this because I have no prior projects? We should find some way to make sure a user who can't use this feature doesn't get confused by it

**Comment by dmorina** [comment]
no there was an overwrite at some point which broke that, Shirish has fixed this last week or so but I think he hasn't pushed yet

DialogController was renamed to something else

**Comment by dmorina** [comment]
fixed on develop2
