### ISSUE TITLE
Delay in displaying details of user profile and default text for completed projects

### ISSUE THREAD

**Issue by sarmatejas1006** [crowdresearch/crowdsource-platform#764]
When the profile is new, shouldn't it show as **"No projects yet"** instead of **"All completed projects"**

![image](https://cloud.githubusercontent.com/assets/12610915/17746139/687c869e-64cc-11e6-8911-c2b271380fd3.png)

**Comment by sarmatejas1006** [comment]
There is a significant delay in displaying the profile details when the **"<Name>"** tab on the top right corner is clicked. It is blank for a few milliseconds before the details appear

These screenshots have been taken in quick succession

![image](https://cloud.githubusercontent.com/assets/12610915/17746172/8a7a2666-64cc-11e6-9d78-db979b069f82.png)

![image](https://cloud.githubusercontent.com/assets/12610915/17746181/92cf2d0c-64cc-11e6-95af-ee280e8e1fde.png)

**Comment by shirishgoyal** [comment]
All completed projects hidden till we actually start showing them

**Comment by shirishgoyal** [comment]
Profile and Financial Accounts section do not appear until we have the details
