### ISSUE TITLE
Navbar dropdown menu position

### ISSUE THREAD

**Issue by sarmatejas1006** [crowdresearch/crowdsource-platform#767]
The navbar dropdown menu can be collapsed a bit lower, below the dropdown arrow

![image](https://cloud.githubusercontent.com/assets/12610915/17746653/a39903b8-64ce-11e6-972d-102b7bdd84b8.png)

![image](https://cloud.githubusercontent.com/assets/12610915/17746624/7c349f8a-64ce-11e6-8ef7-f0b2d85c9b19.png)

**Comment by dmorina** [comment]
it's the default behavior of angular material
