### ISSUE TITLE
Requester Edit Profile Page Bug: Unable to move back in time through calendar

### ISSUE THREAD

**Issue by qwertyone** [crowdresearch/crowdsource-platform#768]
![image](https://cloud.githubusercontent.com/assets/6076358/17746679/7c199888-64b1-11e6-8895-960a1ff0b971.png)

As I was editing the profile and updating my birth information, I notice that the calendar makes it impossible for me to go back in years unless I have explicitly typed the date in the field prior to opening it.

![image](https://cloud.githubusercontent.com/assets/6076358/17746699/a1cde1ec-64b1-11e6-8926-8b394294d022.png)

When the date is typed and then the calendar opened, the alignment of the MONTH field is flush with the first week of the month vertically and horizontally under Sunday, which may pose a problem when the month and the date overlap.

**Comment by shirishgoyal** [comment]
Updated version of material design has new calendar implementation which resolves the issue

![image](https://cloud.githubusercontent.com/assets/315012/17906371/db9dfa28-692b-11e6-84d1-9712fd748556.png)
