### ISSUE TITLE
Job Title returns no information in profile after user typed entry

### ISSUE THREAD

**Issue by qwertyone** [crowdresearch/crowdsource-platform#770]
Job Title works when the requester matches a pre-populated job title.

![image](https://cloud.githubusercontent.com/assets/6076358/17746868/81907d08-64b2-11e6-955e-234b30f36e7e.png)

However, the requester might create a custom job title. 

![image](https://cloud.githubusercontent.com/assets/6076358/17746898/9f7bed3e-64b2-11e6-8e19-6da40ca1ea9e.png)

After typing the title and clicking to save the information for presentation, the change fails to appear.

![image](https://cloud.githubusercontent.com/assets/6076358/17746931/bc78fe7c-64b2-11e6-84bb-1ca7c3764cdc.png)

**Comment by dmorina** [comment]
removing from the profile for now
