### ISSUE TITLE
Workers / Task and $ / Task are unclear

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/crowdsource-platform#773]
These two parameters use the notion of 'task' differently. 

The first one is how many workers should complete each of a set of possibly 1 and possibly many tasks that are unique instances of the same task with some variable being adjusted. In this way the 'task' is a given unique version of an instance of work.

The second one asks how much should we pay for a given piece of labor by a worker, independent of it being part of a task that has several workers working on it.

Also including a realtime sum of how many individual units of work there actually are based on these parameters, as well as the total cost of the project, might help significantly.

**Comment by dmorina** [comment]
@mbernst

**Comment by mbernst** [comment]
It might be best to elide the issue?

Workers per task
Payment

I like the idea (@leonardykris also suggested) about dynamically calculating a summary in a div right below:
"3 workers x $0.14 = $0.42 per task"

**Comment by shirishgoyal** [comment]
Change $/task to Price
Add $ to field value
Restrict decimal places to 2
Show price per task on value updates

**Comment by leonardykris** [comment]
Should we use _Price_? _Reward_ sounds more accurate since the requester is paying it out.
