### ISSUE TITLE
Minutes Allotted is unclear

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/crowdsource-platform#774]
A tool tip or a better heading would help convey that when this times out the task expires.

**Comment by dmorina** [comment]
@mbernst ref #747

**Comment by mbernst** [comment]
"Time limit per task"?

**Comment by shirishgoyal** [comment]
![image](https://cloud.githubusercontent.com/assets/315012/17952019/90c65da6-6a1b-11e6-9dae-5bafb4d6b429.png)

Updated text

**Comment by dmorina** [comment]
@shirishgoyal  i think the different label format was the initial problem the (in min.)
so we have to go for something else

**Comment by dmorina** [comment]
"Minutes allotted per task" we can change it later again if we want to
