### ISSUE TITLE
Feature to change the question type and retain the information already entered

### ISSUE THREAD

**Issue by leonardykris** [crowdresearch/crowdsource-platform#776]
Is there a way to change the type of questions midway after entering the title and still retain the texts? The current available method is to create a new question and then copy the content of the original question over to the newly generated one. This seems unintuitive.

**Comment by dmorina** [comment]
you can change the question type if it's of the same type, but not otherwise. e.g select list, radio, and checkbox are all selection items

**Comment by leonardykris** [comment]
Is there a reason why it's not possible to retain at least the question title on text <-> selection type change? (it's really Google Form-ish)

![daemo_question_type_change](https://cloud.githubusercontent.com/assets/6095903/17794489/a4986aa6-6564-11e6-9469-e58ac756d22e.gif)

**Comment by dmorina** [comment]
i guess that's not expected but we can change it, sure, going from select to text and back to select would mean that only the question is retained the options would be gone!

**Comment by dmorina** [comment]
i put this into the backlog, we will do it later

**Comment by dmorina** [comment]
will reopen if necessary
