### ISSUE TITLE
Task preview

### ISSUE THREAD

**Issue by leonardykris** [crowdresearch/crowdsource-platform#777]
Is it possible to generate a view of how the task will look like when it's posted on AMT for user assurance purposes? It's a familiar pattern in ecommerce sites where you can view the list of items you ordered before checking out.

![screen shot 2016-08-18 at 5 08 47 pm](https://cloud.githubusercontent.com/assets/6095903/17794688/8aa51a2a-6566-11e6-9c1c-bd7980bec50a.png)

![screen shot 2016-08-18 at 5 08 57 pm](https://cloud.githubusercontent.com/assets/6095903/17794694/93654bf8-6566-11e6-9bd5-c78a1be59a1d.png)

**Comment by dmorina** [comment]
we don't have data to preview so it's exactly the same as the view on the authoring page
