### ISSUE TITLE
Show timestamp on projects listed

### ISSUE THREAD

**Issue by leonardykris** [crowdresearch/crowdsource-platform#778]
A timestamp feels like a pretty natural thing to be shown when a collection of items are involved to inform the user of the time the item was created/sent/published.

![screen shot 2016-08-18 at 5 08 05 pm](https://cloud.githubusercontent.com/assets/6095903/17794665/619cd87a-6566-11e6-8f59-97fde8a4d077.png)

**Comment by dmorina** [comment]
+1 i agree to having one time stamp
