### ISSUE TITLE
Add the sum of cash out amount

### ISSUE THREAD

**Issue by leonardykris** [crowdresearch/crowdsource-platform#779]
![screen shot 2016-08-18 at 5 28 09 pm](https://cloud.githubusercontent.com/assets/6095903/17794998/3b265466-6569-11e6-8b58-533982f764b0.png)
In this case, it'd be great if there's a text/message showing that: 
`This project will accept up to 2 workers with a total sum of $1 in reward`

**Comment by dmorina** [comment]
since we are doing api client only the tasks do not exist yet at this point so the total is not that useful, if we were to display a total amount somewhere my suggestion would be "my projects" if that's doesnt have too much info already
