### ISSUE TITLE
Include the information of the original copy

### ISSUE THREAD

**Issue by leonardykris** [crowdresearch/crowdsource-platform#780]
Since the current flow of duplicating a project is:
1. Click "create as copy"
2. Modify the project information (title, questions)
3. Save (or Submit)

And the expected users' intention when they created a new project with a copy are to:
1. Modify some details, or
2. Launch the projects to different worker groups, or
3. Edit rewards

It'd be nice to include information such as the project key to enable user to trace back the original copy or perhaps group those projects together. 

![screen shot 2016-08-19 at 1 40 19 pm](https://cloud.githubusercontent.com/assets/6095903/17823727/dd026f28-6612-11e6-8fb0-6490418f4056.png)

![screen shot 2016-08-19 at 1 42 25 pm](https://cloud.githubusercontent.com/assets/6095903/17823726/dd023a12-6612-11e6-8fcb-3e2b63fd5ab0.png)

**Comment by dmorina** [comment]
not that relevant in this context (we might have too much info on this screen)
