### ISSUE TITLE
Floating overlay is floating away

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#799]
<img width="863" alt="screen shot 2016-09-07 at 9 10 38 am" src="https://cloud.githubusercontent.com/assets/249285/18319541/fcf5d780-74da-11e6-9a1e-1f0dca014720.png">

**Comment by dmorina** [comment]
should be fixed now (?) retest and reopen if it happens again
tested on Chrome and FF and that good good Safari
