### ISSUE TITLE
Field name doesn't change when field type is changed

### ISSUE THREAD

**Issue by shirishgoyal** [crowdresearch/crowdsource-platform#802]
![image](https://cloud.githubusercontent.com/assets/315012/18362330/34a7843c-75ba-11e6-8350-1dfaaebdc378.png)

**Comment by dmorina** [comment]
well, it's difficult because you have to know if the user has changed it from the default one
and they might not want the field name to change if they have edited it once

i would say not an issue for now

**Comment by shirishgoyal** [comment]
How about we rename the fields to something generic like field_1?
