### ISSUE TITLE
add reCAPTCHA to Registration 

### ISSUE THREAD

**Issue by neilthemathguy** [crowdresearch/crowdsource-platform#81]
##  
>1. Integrate [reCAPTCHA](https://www.google.com/recaptcha/intro/index.html) with current registration. 

___________________________________________________________________________________
### Related issues
#44 
___________________________________________________________________________________
### Assigned 

GROUP 1

GROUP 2

___________________________________________________________________________________
### DRI
@neilthemathguy  @dmorina @nistala

**Comment by ankita2992** [comment]
My teammate , @AditiNath  and I would like to work on this issue..... @neilthemathguy

**Comment by dmorina** [comment]
Sure just go for it, try to build this feature as an independent one so that we can reuse it wherever we need to, thanks
