### ISSUE TITLE
Some variables do not appear after task has been modified

### ISSUE THREAD

**Issue by shirishgoyal** [crowdresearch/crowdsource-platform#813]
![image](https://cloud.githubusercontent.com/assets/315012/18363348/967a20c6-75be-11e6-8811-4a3f4e0f8f80.png)

![image](https://cloud.githubusercontent.com/assets/315012/18363421/e3a7d906-75be-11e6-9bd0-ca4cb7455527.png)

**Comment by dmorina** [comment]
fixed, some of the variables were integers
