### ISSUE TITLE
Task design changes launch a new set of tasks

### ISSUE THREAD

**Issue by shirishgoyal** [crowdresearch/crowdsource-platform#816]
- New variables being added to task
- Creates new set of tasks
- Publish with new data set (with additional variables which were added) creates another set of tasks

**Comment by dmorina** [comment]
how to replicate? :D

**Comment by dmorina** [comment]
can you add details to this issue?

**Comment by shirishgoyal** [comment]
Not reproducible anymore. Closing the issue.
