### ISSUE TITLE
AWS keys are showing up as invalid

### ISSUE THREAD

**Issue by shirishgoyal** [crowdresearch/crowdsource-platform#817]
![image](https://cloud.githubusercontent.com/assets/315012/18363971/43e3938a-75c1-11e6-8a4e-d2039600aa45.png)

**Comment by dmorina** [comment]
not sure what the issue was, seems to be working, if it happens again we will look into it

**Comment by shirishgoyal** [comment]
Even though it is not happening now, it should be showing right error message as we get back from MTurk

**Comment by dmorina** [comment]
unfortunately AWS returns the same message for all errors (policy missing or invalid credentials)

i updated the error message to "Invalid keys or missing AmazonMechanicalTurkFullAccess policy, please try again."
