### ISSUE TITLE
"Approve All" for entire project

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#822]
Right now I have to go in and individually approve for each task. Can I just approve all?
<img width="500" alt="screen shot 2016-10-04 at 9 04 21 pm" src="https://cloud.githubusercontent.com/assets/249285/19100991/b75b0b38-8a78-11e6-96d5-ef0732604f97.png">

I think that button only approves within the task.

**Comment by dmorina** [comment]
that is correct

**Comment by mbernst** [comment]
would love to have an "approve all" for the project

**Comment by dmorina** [comment]
ok!
