### ISSUE TITLE
Username generator

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/crowdsource-platform#83]
When registering the system will give the user a username, that will be firstname.lastname, but only if the username does not exist yet.
Write an algorithm which generates a username in case the default pattern is taken by another user. This is based on the first name and last name, so if username firstname.lastname already exists it would use firstname.lastname1 or something like this. The user would be able to change this later on his profile/settings.

DRI @dmorina @neilthemathguy

**Comment by Soroosh129** [comment]
This idea comes from a lazy guy, but couldn’t the username be the email address?


On May 23, 2015 at 2:28:13 AM, Durim Morina (notifications@github.com) wrote:

When registering the system will give the user a username, that will be firstname.lastname, but only if the username does not exist yet.
Write an algorithm which generates a username in case the default pattern is taken by another user. This is based on the first name and last name, so if username firstname.lastname already exists it would use firstname.lastname1 or something like this. The user would be able to change this later on his profile/settings.

**Comment by angelamayx** [comment]
Couldn't they pick their own usernames?

**Comment by dmorina** [comment]
@Soroosh129 currently if the username is taken then the email is used as a username.
we want usernames because emails are not good to be used in url lookups

@angelamayx they could do that while registering but I think we should keep registration form as short as possible, they will be able to change it later anyways..

**Comment by v1p** [comment]
@dmorina Purpose of username is only to give a an SEO-friendly url to the user for his/her profile ?

**Comment by dmorina** [comment]
there are few benefits of using a custom username: multiple ways to login, friendly urls, you can browse other users easily by using a username

**Comment by shirishgoyal** [comment]
Another reason for not using emails is that most of the workers or requesters do not want to share their emails on the public pages of platform so username is used mostly for display purposes.
