### ISSUE TITLE
Layout bug for revision selector on worker review

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#840]
<img width="218" alt="screen shot 2017-06-05 at 4 38 33 pm" src="https://cloud.githubusercontent.com/assets/249285/26807796/77d264fc-4a0d-11e7-94a9-64e89910467c.png">

**Comment by dmorina** [comment]
<img width="504" alt="screen shot 2017-06-05 at 4 40 19 pm" src="https://cloud.githubusercontent.com/assets/2858281/26807841/b37a92b8-4a0d-11e7-94d3-e6f462f9310d.png">

**Comment by dmorina** [comment]
i dont understand Chrome, really, it's the basic stuff padding/margin
