### ISSUE TITLE
Project 20 has a huge amount of whitespace at the bottom of its preview

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#847]
Low priority. Not sure what's up with the spacing. Haven't bothered to isolate the bug yet...may be a particular kind of form input?

Video:
![preview-whitespace 1](https://user-images.githubusercontent.com/249285/26955436-955483e2-4c6b-11e7-91a4-eb84d1dcab84.gif)

Browser: Chrome

**Comment by dmorina** [comment]
It's YUGE because the animation needs the height to be set and we calculate it using an average height * number of components + some margin; haven't looked too deep into this to see if there's a way without specifying the height

**Comment by mbernst** [comment]
Suggested solution: launch previews in a new tab

**Comment by shirishgoyal** [comment]
Added fix for space (without depending on height explicitly) and handle scrolling to top on preview
