### ISSUE TITLE
After copying a task, it is still linked to its old discussion thread

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#855]
I duplicated my prototype task to create my final task, then launched it. I clicked the button to create the comment thread. But it just launched the thread for the original prototype task. Now the workers for the final task are seeing the feedback on the prototype task. :( 

Duplicating a task should not duplicate its link to the comment thread. Clicking comment should start a new thread for the new task.

**Comment by shirishgoyal** [comment]
Removed the link to previous threaded discussion. It will start with a new one every time project is forked.
