### ISSUE TITLE
Worker Input Form Field Errors

### ISSUE THREAD

**Issue by qwertyone** [crowdresearch/crowdsource-platform#862]
![image](https://user-images.githubusercontent.com/6076358/27156113-f5a88492-515b-11e7-97cb-23ef1c9b164d.png)

from: https://daemo-test.herokuapp.com/getting-started

potential user errors: users can insert an infinite series of numbers and letters in worker setup text fields.
the text field requiring the last four of the SSN allows greater than 4 non-numeric characters.

In a situation when the user introduces either false, error filled, or foreign information, this instance of Daemo will not complete the transaction with Stripe and will keep spinning in the upper part of the window under the heading box.

![image](https://user-images.githubusercontent.com/6076358/27156287-bd35b50c-515c-11e7-8cc5-d7ea561c9643.png)

**Comment by dmorina** [comment]
yes, once you submit the form there will be an error telling you that the values are invalid.. closing
