### ISSUE TITLE
Autopopulated forum post doesn't correctly tag the requester

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#871]
I'm not sure why it didn't work: https://forum.daemo.org/t/find-career-information-about-an-mit-computer-science-phd-graduate/150

It has my handle correct, I think? @shirishgoyal what's going on?

**Comment by shirishgoyal** [comment]
It was missing a space at end of the requester name. 
Also converted format to markdown and added category "Tasks" to all projects

**Comment by dmorina** [comment]
is this resolved @shirishgoyal ?

**Comment by shirishgoyal** [comment]
Yes, this was resolved. I am checking on a different issue of setting requester to auto-watch the topic
