### ISSUE TITLE
Provide UI feedback when the user presses "Publish"

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#876]
Right now there is no reaction, then the system eventually moves back to the task feed. Better: when they hit "publish", disable the button and change its text to "Publishing..." until complete, then route back to the task feed when complete.

**Comment by dmorina** [comment]
so it shouldn't route to `Requester Status` as it does now?

**Comment by mbernst** [comment]
It should. Sorry, replace "Task Feed" with "Requester Status" above. What I meant to say was just that the button should react when I click "Publish" to give me feedback, before that routing happens.
