### ISSUE TITLE
New Task emails to focus on the TASK  

### ISSUE THREAD

**Issue by iceLearn** [crowdresearch/crowdsource-platform#879]
Mails on new task - 
![tasks mails](https://user-images.githubusercontent.com/12571844/27339786-5b8e2fde-55f6-11e7-983c-f87896f32afa.png)
Currently every mail on new task  has 
> Hi, 
Daemo is starting out as a small marketplace, so instead of asking workers to track the task feed all the time, we notify you when new work is available. The following task is now accessible to you. The higher ratings you get from requesters, the earlier you get access to these tasks. 

Can we change the email layout so it focus on the New task more.
Proposing following - 
![new email task](https://user-images.githubusercontent.com/12571844/27340517-4d7dadc8-55f8-11e7-872a-01a5c1480f7e.png)

**Comment by dmorina** [comment]
fixed
