### ISSUE TITLE
Make it possible to retroactively add academic account information

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/crowdsource-platform#882]
Users who've created accounts with other email addresses should be able to switch to academic addresses in order to utilize academic discounts.

**Comment by dmorina** [comment]
I think if you have #881 in place you dont really need this, it's just too much work for what we get out of it, they might just create a different account then or if they miss it in the homepage or sign up form (after we add it) it's kind of their fault so that's ok :D

**Comment by markwhiting** [comment]
OK. I'll close.
